### PR TITLE
tests/misc-ro: drop `rpm-ostree ex module install` test

### PR DESCRIPTION
**Pull request by jlebon**
Thought this was cool to have here, but first it needs Internet, which
the rest of `misc-ro` doesn't so far which is nice. And second each
Fedora version has different stream versions so the matrix is slightly
trickier.

I think I'll put it in the rpm-ostree testsuite instead. Anyway if we
really go the modularity route for cri-o, ideally we'd have some k8s
testing going on in CI here on top of OKD or Typhoon, and then this will
implicitly be tested.

### CODE REVIEW

**Comment by jlebon** [comment]
> Thought this was cool to have here, but first it needs Internet, which
> the rest of `misc-ro` doesn't so far which is nice.

I think the reason this worked originally in https://github.com/coreos/fedora-coreos-config/pull/1191 was because of https://github.com/coreos/coreos-assembler/pull/2356, which bundled misc-ro with other non-exclusive tests which do require networking.

**Review by bgilbert — APPROVED** [review]

**Comment by dustymabe** [comment]
why can't we make this it's own separate test and just mark it as needing internet? I think the test is still valuable.

**Comment by jlebon** [comment]
> why can't we make this it's own separate test and just mark it as needing internet? I think the test is still valuable.

We can... I'm just hesitant to add tests which depend on outside resources. Not planning to get rid of the test, just moving it to rpm-ostree. Edit: https://github.com/coreos/rpm-ostree/pull/3123

**Comment by dustymabe** [comment]
Yeah. I think if cri-o is a part of our solution to https://github.com/coreos/fedora-coreos-tracker/issues/767 then we probably at least want to verify it layers find on each build. WDYT?

**Comment by jlebon** [comment]
> Yeah. I think if cri-o is a part of our solution to [coreos/fedora-coreos-tracker#767](https://github.com/coreos/fedora-coreos-tracker/issues/767) then we probably at least want to verify it layers find on each build. WDYT?

I think that makes sense, though ideally as mentioned earlier we sanity-test OKD or Typhoon in CI instead.

**Pull request merged**
