### PR TITLE
overrides: pin kernel-6.8.11-300.fc40

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @jbtrystram via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
It complains on the kernel being downgrade, which is intentional.

**Comment by jbtrystram** [comment]
how can I override the test to merge ?
```
[2024-06-27T10:15:49.393Z] ostree diff commit from: 4387817a5544a3e594c9e48841c8a6d33d31d35c0e4196812db132a551f1a368
[2024-06-27T10:15:49.393Z] ostree diff commit to:   25cc107f3b1316b73b2f7614a62fb123cf7d6d01d76149671ebed455f56770a1
[2024-06-27T10:15:49.393Z] Downgraded:
[2024-06-27T10:15:49.393Z]   kernel 6.9.5-200.fc40 -> 6.8.11-300.fc40
[2024-06-27T10:15:49.393Z]   kernel-core 6.9.5-200.fc40 -> 6.8.11-300.fc40
[2024-06-27T10:15:49.393Z]   kernel-modules 6.9.5-200.fc40 -> 6.8.11-300.fc40
[2024-06-27T10:15:49.393Z]   kernel-modules-core 6.9.5-200.fc40 -> 6.8.11-300.fc40
[2024-06-27T10:15:49.393Z] + grep -q Downgraded tmp/diff.txt
[2024-06-27T10:15:49.393Z] + echo 'Downgrade detected. This is likely unintentional. If not, you may safely ignore this error.'
[2024-06-27T10:15:49.393Z] Downgrade detected. This is likely unintentional. If not, you may safely ignore this error.
```

**Review by jlebon — APPROVED** [review]
There is no override. We merge over red. :)
This is why the check runs last; everything else passed.

**Comment by jbtrystram** [comment]
> There is no override. We merge over red. :) This is why the check runs last; everything else passed.

ok, the merge button wasn't really explicit so I wasn't sure it would merge !

**Pull request merged**
