### PR TITLE
tests/root-reprovision: Query `/sysroot`, not `/`

### PR DESCRIPTION
**Pull request by cgwalters**
Prep for enabling composefs.  This is the same issue as https://github.com/coreos/coreos-installer/pull/1203

### CODE REVIEW

**Comment by cgwalters** [comment]
Ah, CI failure looks like unrelated fallout:

> [    4.073776] ignition[1282]: files: createFilesystemsFiles: createFiles: op(3): Error fetching file "/sysroot/etc/NetworkManager/dispatcher.d/30-timesyncd": resource not found

Ah, I see https://github.com/eworm-de/networkmanager-dispatcher-timesyncd/raw/master/30-timesyncd ceased to exist.  Because of https://github.com/eworm-de/networkmanager-dispatcher-timesyncd/commit/bdeed3f9f6e18d53e960635d148764a1f8f83ea2 presumably but that claims to have been committed years ago.  Confusing.

Anyways, here is the peril of having our gating tests depending on random uncontrolled internet resources...

**Comment by dustymabe** [comment]
> Ah, CI failure looks like unrelated fallout:
> 
> > [    4.073776] ignition[1282]: files: createFilesystemsFiles: createFiles: op(3): Error fetching file "/sysroot/etc/NetworkManager/dispatcher.d/30-timesyncd": resource not found
> 
> Ah, I see https://github.com/eworm-de/networkmanager-dispatcher-timesyncd/raw/master/30-timesyncd ceased to exist. Because of [eworm-de/networkmanager-dispatcher-timesyncd@bdeed3f](https://github.com/eworm-de/networkmanager-dispatcher-timesyncd/commit/bdeed3f9f6e18d53e960635d148764a1f8f83ea2) presumably but that claims to have been committed years ago. Confusing.
> 
> Anyways, here is the peril of having our gating tests depending on random uncontrolled internet resources...

https://github.com/coreos/fedora-coreos-config/pull/2782

**Comment by dustymabe** [comment]
> Prep for enabling composefs

Worth noting that soon we will be switching to OSBuild for image builds, which may have implications here.

**Review by dustymabe — APPROVED** [review]
These changes LGTM

**Pull request merged**
