### PR TITLE
WIP: NM in the initrd

### PR DESCRIPTION
**Pull request by cgwalters**
This seems not to run for me...I don't quite understand the
initqueue stuff, still debugging.

See also https://github.com/coreos/fedora-coreos-config/pull/200#issuecomment-544592432

Blocked on: https://github.com/dracutdevs/dracut/issues/694

### CODE REVIEW

**Comment by cgwalters** [comment]
xref https://bugzilla.redhat.com/show_bug.cgi?id=1787620

**Comment by cgwalters** [comment]
I've verified that we have the module code in the initrd, but it looks like the initqueue never executes `/usr/lib/dracut/hooks/initqueue/settled/99-nm-run.sh` (I added an `echo` statement to that code).

**Comment by thom311** [comment]
hm. Is there no further information here? Any logs?

What was the kernel command line?

If you don't even get 99-nm-run.sh to execute, then it's a dracut issue (or an issue in NM's dracut module).

**Comment by dustymabe** [comment]
since I'm having networking in the initrd troubles myself, I can try testing this out to see if I get any different results.

**Comment by cgwalters** [comment]
OK so...this is a bit obvious now, but entering `emergency.target` will kill other services - specifically it will kill `dracut-initqueue.service`.  So to better replicate what's going on in the normal case, be sure to  at least `systemctl start dracut-initqueue`.

**Comment by cgwalters** [comment]
> hm. Is there no further information here? Any logs?
> What was the kernel command line?

`rd.neednet ip=dhcp` are the relevant bits.

I can paste the full journal if you want (it's also easy to do a FCOS build from this patch) but AFAICS there's nothing there of use because:

> If you don't even get 99-nm-run.sh to execute, then it's a dracut issue (or an issue in NM's dracut module).

Right.  That's as far as I got - it's not clear to me why that hook isn't being executed.  I don't understand the initqueue really to be honest.

**Comment by cgwalters** [comment]
xref https://github.com/dracutdevs/dracut/pull/702

**Comment by cgwalters** [comment]
As best I can tell what's happening is `/usr/bin/dracut-initqueue` is calling `check_finished` which looks for files in `$hookdir/initqueue/finished/` - and since nothing is there, we exit before trying any of the other hooks.

It seems like other dracut initrd code is dropping files there, but the NM initrd code isn't.

Was this NM initrd code ever tested?  If so, where?

**Comment by ryncsn** [comment]
Hi, for the dracut problem I have filed an issue that is related to your problem sometime ago, maybe we can discuss there:
See https://github.com/dracutdevs/dracut/issues/694

**Comment by cgwalters** [comment]
@ryncsn Thank you, that looks exactly like the bug!

**Comment by jlebon** [comment]
Blocked on: https://github.com/dracutdevs/dracut/issues/694.

**Comment by LorbusChris** [comment]
Hopefully this'll be unblocked with the next dracut build :)

**Comment by dustymabe** [comment]
Now that https://github.com/dracutdevs/dracut/issues/694 is fixed I'm picking this up and running with it. I'm going to close this out and open a new PR with more fixes in it.

**Comment by dustymabe** [comment]
If you'd like to track progress on this you can follow https://github.com/coreos/fedora-coreos-tracker/issues/394

**Pull request closed without merging**
