### PR TITLE
CI test for podman 1.9.0-0.4.rc1.fc31

### PR DESCRIPTION
**Pull request by dustymabe**
This is purely to test out an rc candidate of podman and give feedback
to the team based on the PR.

### CODE REVIEW

**Comment by cgwalters** [comment]
No objections to this, but it seems easier to just drop the RPMs in `overrides/rpm` locally and `cosa build` + `kola run` if that's what's desired.

**Comment by cgwalters** [comment]
And what we *really* want to do of course is run podman's own test suite as [external kola tests](https://github.com/coreos/coreos-assembler/blob/a3e04d6a7bf75fa1d92dc33b932688f7c66ef2a6/mantle/kola/README-kola-ext.md)

**Comment by dustymabe** [comment]
This CI test seems to have found a bug in the potential podman 1.9 rc. Great job CI. The error is similar to https://github.com/containers/crun/issues/275 and easily reproducible on any system in cgroups v1 mode. The podman team is investigating.

**Comment by dustymabe** [comment]
> No objections to this, but it seems easier to just drop the RPMs in `overrides/rpm` locally and `cosa build` + `kola run` if that's what's desired.

yeah I thought about that. There is a level of automation here that is real nice (for one I don't have to `koji download-build`). Also it is nice to have the logs publicly viewable in case they need to be shared.

In the future @baude can actually open a PR like this himself if he wants to test out an RC

**Comment by dustymabe** [comment]
this is reported fixed by a newer crun: https://bodhi.fedoraproject.org/updates/FEDORA-2020-6191838a57

I added another commit to add the new crun. Let's see if it fixes it.

**Comment by dustymabe** [comment]
@baude - tests passed! https://jenkins-coreos-ci.apps.ci.centos.org/job/github-ci/job/coreos/job/fedora-coreos-config/job/PR-345/2/display/redirect

I'll close this out now

**Comment by dustymabe** [comment]
and testing with the non-rc podman 1.9 passed too! https://jenkins-coreos-ci.apps.ci.centos.org/job/github-ci/job/coreos/job/fedora-coreos-config/job/PR-345/3/display/redirect

closing again

**Pull request closed without merging**
