### PR TITLE
test/kola: Test disabling units via Ignition

### PR DESCRIPTION
**Pull request by travier**
Test for: https://github.com/coreos/fedora-coreos-tracker/issues/392

### CODE REVIEW

**Review by sohankunkerkar — COMMENTED** [review]
Thanks for handling this!
code LGTM, I think CI needs the latest version of Ignition (v2.14.0)

**Comment by bgilbert** [comment]
LGTM pending Ignition update.

**Review by dustymabe — DISMISSED** [review]

**Comment by bgilbert** [comment]
Needs rebase to pick up Ignition fast-track.

**Comment by travier** [comment]
Rebased

**Review by bgilbert — APPROVED** [review]

**Review by sohankunkerkar — APPROVED** [review]

**Pull request merged**
