### PR TITLE
ci & tests: Switch to quay.io/fedora/fedora

### PR DESCRIPTION
**Pull request by travier**
Fedora is planning on deprecating the registry and moving to quay.io for
all containers.

Existing containers are mirrors to quay.io so we should be able to
switch now.

See: https://discussion.fedoraproject.org/t/registry-fedoraproject-org-to-quay-io-migration/88231
See: https://pagure.io/fedora-infrastructure/issue/10386

### CODE REVIEW

**Comment by travier** [comment]
Based on https://github.com/coreos/fedora-coreos-config/pull/2622 to simplify rebases. We don't have to do it now.

**Review by jlebon — DISMISSED** [review]

**Comment by jlebon** [comment]
There's also https://github.com/coreos/fedora-coreos-config/blob/745417d2a51ad93ceea02510550dd3336c3f525a/.github/workflows/add-override.yml#L40 we might as well change while we're here.

**Review by jlebon — DISMISSED** [review]

**Comment by dustymabe** [comment]
Let's rebase this and get it merged.

**Comment by travier** [comment]
Rebased

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
