### PR TITLE
[next-devel] overrides: drop graduated overrides

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
re-kicked CI

**Comment by jlebon** [comment]
This is failing on the multipath test because this branch is missing the [Ignition fast-track](https://github.com/coreos/fedora-coreos-config/pull/1034).

Could cherry-pick here for the benefit of CI, though since this stream is currently disabled... let's just drop that bit from the issue template?

**Comment by bgilbert** [comment]
Yeah, I wondered about that.  If we're going to let the overrides go stale in this branch, another approach is to force-merge this PR, then the checklist entry becomes a no-op.

**Comment by jlebon** [comment]
> Yeah, I wondered about that. If we're going to let the overrides go stale in this branch, another approach is to force-merge this PR, then the checklist entry becomes a no-op.

Sure, that SGTM!

**Pull request merged**
