### PR TITLE
overrides: fast-track kdump-utils-1.0.48-1.fc40

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @jbtrystram via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Comment by dustymabe** [comment]
let's open a fast-track for `next-devel` too and just drop the denylist entry here completely?

**Comment by jbtrystram** [comment]
> let's open a fast-track for `next-devel` too and just drop the denylist entry here completely?

https://github.com/coreos/fedora-coreos-config/pull/3219

**Comment by dustymabe** [comment]
the denylist itself has a single source of truth (on the `testing-devel` branch) so you'll need to remove the entry here in this PR.

also if PRs are to the main development branch (which is `testing-devel`) we don't usually prefix the PR title with the branch name.

**Comment by dustymabe** [comment]
> the denylist itself has a single source of truth (on the `testing-devel` branch) so you'll need to remove the entry here in this PR.

fixed in latest push

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
