### PR TITLE
Revert "overlay: add new module for installing Azure udev rules"

### PR DESCRIPTION
**Pull request by miabbott**
This reverts commit 8c07b7391473910ba3884ee0d3763743805ac78f.

The `WALinuxAgent-udev` package now installs the udev rules in the
initrd.

### CODE REVIEW

**Comment by miabbott** [comment]
I verified that the udev rules are in the initrd, but didn't go as far as testing in Azure proper.

**Review by jlebon — APPROVED** [review]

**Comment by jlebon** [comment]
Aren't we relying on this right now in RHCOS though? Or did the fixed `WALinuxAgent` make it there too already?

**Comment by dustymabe** [comment]
Would be nice to have at least one person run it on azure.

**Comment by dustymabe** [comment]
> Aren't we relying on this right now in RHCOS though? Or did the fixed `WALinuxAgent` make it there too already?

If true, might be a candidate for moving that RHCOS specific bit into openshift/os ?

**Comment by miabbott** [comment]
> > Aren't we relying on this right now in RHCOS though? Or did the fixed `WALinuxAgent` make it there too already?
> 
> If true, might be a candidate for moving that RHCOS specific bit into openshift/os ?

Right, the `-udev` package is available in RHEL8, but it doesn't have the script to install the rules in the initrd.

We'd want to carry this deleted code in RHCOS only for now.

**Comment by bgilbert** [comment]
Closing as duplicate of #1686.

**Pull request closed without merging**
