### PR TITLE
[testing] tree: promote changes from testing-devel at 351528ebe9893671ed414fbcf923da42dfa96fd4

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by sinnykumari** [comment]
CI needs rerun, it seems generated metadata is a bit outdated `fedora-coreos-pool'; generated: 2020-06-11`

```
Updating metadata for 'fedora-coreos-pool'...done
rpm-md repo 'fedora-coreos-pool'; generated: 2020-06-11T16:37:24Z
Importing rpm-md...done
error: Couldn't find locked package 'fedora-release-coreos-32-3.noarch' (pkgs matching NEVRA: 0; mismatched checksums: 0)
script returned exit code 1
```

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
Let's use #475 to pick up the new kernel/microcode_ctl for the recent CVE (see #473).

**Comment by sinnykumari** [comment]
closing in favor of https://github.com/coreos/fedora-coreos-config/pull/474

**Pull request closed without merging**
