### PR TITLE
manifests: Move `container-cmd` to `user-experience.yaml`

### PR DESCRIPTION
**Pull request by cgwalters**
I was going to do a PR to add this to openshift/os too, but actually
let's just share it more directly instead!

### CODE REVIEW

**Review by jlebon — APPROVED** [review]
Makes sense to me!

**Comment by dustymabe** [comment]
if possible let's hold this until the current bump-lockfile run finishes: https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/bump-lockfile/66/

**Comment by dustymabe** [comment]
done - this is now unblocked.

**Comment by cgwalters** [comment]
/override continuous-integration/jenkins/pr-merge
Flaked on journal bits

**Pull request merged**
