### PR TITLE
[stable] tree: promote changes from testing at 390d2614cb39769fe9a6aa29ed868ae0e8ac4c62

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by sinnykumari** [comment]
kola run failed:
```kola --denylist-test fcos.internet --denylist-test podman.workflow -p qemu-unpriv --output-dir tmp/kola run --parallel 8
Error: Parsing config.ign: unsupported config version
2020-10-19T14:12:23Z cli: Parsing config.ign: unsupported config version
script returned exit code 1
```

**Review by dustymabe — APPROVED** [review]
the diff LGTM

**Comment by jlebon** [comment]
Can you cherry-pick this commit here: https://github.com/coreos/fedora-coreos-config/commit/dbd761aded66933d6731f7e27b114a1ab379ff9f ?

**Comment by sinnykumari** [comment]
> Can you cherry-pick this commit here: [dbd761a](https://github.com/coreos/fedora-coreos-config/commit/dbd761aded66933d6731f7e27b114a1ab379ff9f) ?

done

**Comment by dustymabe** [comment]
LGTM

**Review by jlebon — APPROVED** [review]

**Pull request merged**
