### PR TITLE
[next] tree: promote changes from next-devel at 736eea98bee584c05b094520e8d3d10abc9ea4ec

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @saqibali-2k in https://github.com/coreos/fedora-coreos-streams/issues/375.

### CODE REVIEW

**Comment by travier** [comment]
@saqibali-2k You should probably try to 'retry' the test job here in the Jenkins UI.

**Comment by dustymabe** [comment]
```
[2021-10-04T14:57:36.690Z] Importing rpm-md...done
[2021-10-04T14:57:36.690Z] rpm-md repo 'coreos-assembler-local-overrides' (cached); generated: 2021-10-04T14:56:51Z solvables: 2
[2021-10-04T14:57:36.690Z] rpm-md repo 'fedora-coreos-pool'; generated: 2021-10-01T21:38:29Z solvables: 20063
[2021-10-04T14:57:36.690Z] error: Couldn't find locked package 'audit-libs-3.0.6-1.fc35.x86_64' (pkgs matching NEVRA: 0; mismatched checksums: 0)
```

When you see failures like this it could mean the [coreos-koji-tagger](https://github.com/coreos/fedora-coreos-releng-automation/tree/main/coreos-koji-tagger) is not behaving properly.

**Comment by dustymabe** [comment]
Yep. Somehow it had lost connection.
```
2021-10-03 19:25:07,098 ERROR pika.adapters.twisted_connection - connection_lost: ConnectionLost('Connection lost')
2021-10-03 19:25:07,102 WARNING fedora_messaging.twisted.protocol - The connection to the broker was lost (ConnectionLost('Connection lost')), consumer halted; the connection should restart and consuming will resume.
```

I cycled it and it's running again now. Will circle back here when things are tagged in properly.

**Comment by travier** [comment]
@saqibali-2k Looks like you triggered the next promote when it was planned that you do the testing one.

**Comment by saqibali-2k** [comment]
> @saqibali-2k Looks like you triggered the next promote when it was planned that you do the testing one.

Ah shoot, I see it. MB on this everyone. Should I leave this open, or close it and remove the label for now?

**Comment by travier** [comment]
I think you can just let @gursewak1997 pick up the next steps

**Review by travier — APPROVED** [review]

**Review by gursewak1997 — APPROVED** [review]

**Pull request merged**
