### PR TITLE
[rhcos-4.18] 07fix-selinux-labels: fix service ordering

### PR DESCRIPTION
**Pull request by mike-nguyen**
This fixes a mistake in b182027. Before/After directives need to go in the [Unit] section, not [Service].

(cherry picked from commit e2c37dbec85c3853424cc31d79f9bfd18ba8a1eb)

Backporting this to the rhcos-4.18 branch per https://github.com/openshift/os/pull/1644#issuecomment-2485860058

### CODE REVIEW

**Comment by dustymabe** [comment]
since zincati doesn't run in RHCOS not sure this will make much of a difference, but will maybe get rid of a warning/log message.

**Review by dustymabe — APPROVED** [review]
/lgtm

**Review by jlebon — APPROVED** [review]
Yeah, this is mostly to ensure there's no warning.

**Comment by jlebon** [comment]
Hmm, CI isn't meaningful here. Let's just get this in?

**Comment by jlebon** [comment]
Wait, I think something got messed up. This is opened against `testing-devel` not `rhcos-4.18`. We of course already have this commit in `testing-devel`, but somehow the GitHub UI made it seem like we didn't. The PR is marked as merged, but AFAICT nothing was actually pushed to `testing-devel`. Hmm, this is possibly by design though it would've been nice to make it clearer in the UI.

Anyway, all this to say, I think we still need a PR against `rhcos-4.18` with that cherry-pick.

**Comment by dustymabe** [comment]
> We of course already have this commit in `testing-devel`, but somehow the GitHub UI made it seem like we didn't.

super weird

**Comment by mike-nguyen** [comment]
Opened https://github.com/coreos/fedora-coreos-config/pull/3276 targeting the correct branch

**Pull request merged**
