### PR TITLE
[stable] tree: promote changes from testing at 5122f0d7f7e024d73b307b8ec922409

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by jlebon** [comment]
Can you add another commit which does https://github.com/coreos/fedora-coreos-streams/issues/94#issuecomment-624637831 ?

**Comment by sohankunkerkar** [comment]
> Can you add another commit which does [coreos/fedora-coreos-streams#94 (comment)](https://github.com/coreos/fedora-coreos-streams/issues/94#issuecomment-624637831) ?

Done!

**Comment by jlebon** [comment]
> Add support for an osmet knob

Maybe:

> Disable osmet generation for now

?

And the commit message can link to https://github.com/coreos/coreos-assembler/pull/1418.

**Review by jlebon — APPROVED** [review]
LGTM!

**Pull request merged**
