### PR TITLE
Move to Fedora Linux 41

### PR DESCRIPTION
**Pull request by dustymabe**
Now that F41 is GA and we are promoting 41 to `testing` let's update `testing-devel` to track F41 content.

### CODE REVIEW

**Comment by aaradhak** [comment]
Looks like the CI failed due to 

```

[2024-10-28T15:53:33.284Z] Updating metadata for 'fedora'...done

[2024-10-28T15:53:33.284Z] error: Installing packages: Updating rpm-md repo 'fedora': cannot update repo 'fedora': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 403 for https://dl.fedoraproject.org/pub/fedora/linux/releases/41/Everything/x86_64/os/repodata/repomd.xml (IP: 10.3.163.84)

[2024-10-28T15:53:34.639Z] failed to execute cmd-fetch: exit status 1

script returned exit code 1
```

**Comment by dustymabe** [comment]
> Looks like the CI failed due to

It will pass tomorrow once releng has moved F41 content into the right place. I'll re-run CI then.

**Comment by aaradhak** [comment]
Also, looks like an empty last line is needed for `manifest-lock-overrides.aarach64.yaml` file

**Review by HuijingHei — APPROVED** [review]
LGTM

**Review by jlebon — APPROVED** [review]
```diff
diff --git a/ci/buildroot/Dockerfile b/ci/buildroot/Dockerfile
index aee83d3e..8277318c 100644
--- a/ci/buildroot/Dockerfile
+++ b/ci/buildroot/Dockerfile
@@ -5,7 +5,7 @@
 #
 # This image is used by CoreOS CI to build software like
 # Ignition, rpm-ostree, ostree, coreos-installer, etc...
-FROM quay.io/fedora/fedora:40
+FROM quay.io/fedora/fedora:41
 # Work around for https://bugzilla.redhat.com/show_bug.cgi?id=2278652
 ENV container=oci
 COPY . /src
diff --git a/kola-denylist.yaml b/kola-denylist.yaml
index 1ff90fb7..d92b2ff3 100644
--- a/kola-denylist.yaml
+++ b/kola-denylist.yaml
@@ -10,16 +10,3 @@
   warn: true
   arches:
     - ppc64le
-- pattern: kdump.crash.nfs
-  tracker: https://github.com/coreos/fedora-coreos-tracker/issues/1820
-  streams:
-     - rawhide
-     - next-devel
-     - next
-- pattern: ext.config.boot.bootupd-validate
-  tracker: https://github.com/coreos/fedora-coreos-tracker/issues/1788
-  snooze: 2024-11-18
-  streams:
-    - stable
-    - testing
-    - testing-devel
diff --git a/manifest.yaml b/manifest.yaml
index 7cde51ad..98d38252 100644
--- a/manifest.yaml
+++ b/manifest.yaml
@@ -1,5 +1,5 @@
 variables:
-  stream: next-devel
+  stream: testing-devel
   prod: false
 
 releasever: 41
@@ -9,8 +9,7 @@ repos:
   # use `cosa fetch --update-lockfile`; but note that all package versions are
   # still pinned. These repos are also used by the remove-graduated-overrides
   # GitHub Action.
-  - fedora-next
-  - fedora-next-updates
-# - fedora-candidate-compose
+  - fedora
+  - fedora-updates
 
 include: manifests/fedora-coreos.yaml
```

**Comment by dustymabe** [comment]
CI here found a downgraded crypto-policies:

```
Downgraded:
  crypto-policies 20241011-1.git5930b9a.fc40 -> 20241010-1.git8baf557.fc41
```

We'll try to work with the maintainers to get a newer version built
for f41.

**Pull request merged**
