### PR TITLE
rhcos-4.6: Backport dhclient changes

### PR DESCRIPTION
**Pull request by LorbusChris**
Backports applicable parts of https://github.com/openshift/os/pull/486 and https://github.com/openshift/os/pull/494

### Requirements

BEFORE MERGING:
- Merge https://github.com/openshift/os/pull/494
- Verification of https://bugzilla.redhat.com/show_bug.cgi?id=1908462

AFTER MERGING:
- Follow up in  in `redhat-coreos` to re-add `dhclient` binaries and bump `fedora-coreos-config` submodule with these changes: https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/merge_requests/1225

/hold

### CODE REVIEW

**Comment by LorbusChris** [comment]
@ashcrow @miabbott should the changes to the `misc-ro` test land here or in https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/blob/4.6/tests/kola/misc-ro/misc-ro.sh?

**Comment by miabbott** [comment]
> @ashcrow @miabbott should the changes to the `misc-ro` test land here or in https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/blob/4.6/tests/kola/misc-ro/misc-ro.sh?

For 4.6, I believe the `misc-ro` tests are defined in the `redhat-coreos` repo.  

(Though there is a difference between the tests defined there and here in f-c-c; might be worthwhile to explore moving the missing tests from f-c-c to `redhat-coreos`)

**Comment by LorbusChris** [comment]
This PR is required before merging https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/merge_requests/1225

**Review by jlebon — APPROVED** [review]
LGTM. I'm assuming you've tested this on 4.6 too, right?

**Comment by LorbusChris** [comment]
I haven't tested it manually, but a pipeline should be running now with these updates over on Gitlab: https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/merge_requests/1225

/hold
for results of that

**Comment by LorbusChris** [comment]
The pipeline over at https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/merge_requests/1225 has passed with these changes.
I believe this is ready to go!

**Comment by miabbott** [comment]
Late breaking nit:  could you link the 4.6.z BZ in one of the commit messages - https://bugzilla.redhat.com/show_bug.cgi?id=1915997

**Comment by LorbusChris** [comment]
@miabbott I've added it to the first commit message

**Comment by jlebon** [comment]
CI won't pass here because it's trying to build an old FCOS.

**Pull request merged**
