### PR TITLE
[stable] tree: promote changes from testing at 0d7d22fb781f5a42ba98f4947b54efe1c39beef7

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @jlebon in https://github.com/coreos/fedora-coreos-streams/issues/789.

### CODE REVIEW

**Review by marmijo — DISMISSED** [review]
LGTM

**Comment by jlebon** [comment]
I'm not sure, but I think the `peter-evans/create-pull-request` action got confused by the promotion and revert of the promotion in https://github.com/coreos/fedora-coreos-config/pull/2664 and thought that it didn't have to update `stable-promotion` branch to the latest `stable` base. This bit of the GHA logs looks suspicious:

> 2023-10-16T21:05:14.2931610Z [command]/usr/bin/git rev-list --left-only --count fork/stable-promotion...stable-promotion
> 2023-10-16T21:05:14.2967312Z 0
> 2023-10-16T21:05:14.2972648Z Branch 'stable-promotion' is even with its remote and will not be updated

So I manually updated this PR for now. I think one way to fix this is to force-push to the fork's branch before calling out to the `create-pull-request` Action.

**Comment by marmijo** [comment]
Thank you @jlebon!

**Review by marmijo — APPROVED** [review]
LGTM

**Pull request merged**
