### PR TITLE
overrides: fasttrack coreos-installer 0.1.3-1.fc31.x86_64

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Review by dustymabe — APPROVED** [review]

**Comment by jamescassell** [comment]
Great, but why?

**Comment by dustymabe** [comment]
> Great, but why?

so we can test the installer in our development stream for more time before it hits our testing stream and then our stable stream.

**Comment by jamescassell** [comment]
Yes makes sense. I should have checked the branch.

**Comment by jlebon** [comment]
Can you add a link to the Bodhi update? It's helpful for tracking when to remove the override (so long as it's humans doing that job).

Edit: accompanied by a short rationale. :)

**Pull request merged**
