### PR TITLE
[rawhide] overrides: fast-track rpm-ostree-2022.4-1.fc37

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @dustymabe via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Review by dustymabe — DISMISSED** [review]

**Comment by dustymabe** [comment]
Will have someone else review this one too since I added a second commit on top.

**Comment by dustymabe** [comment]
hmm - CI is failing with:
```
[2022-03-03T02:47:24.981Z] error: Executing %transfiletriggerin for glibc-common: Package 'glibc-common' has (currently) unsupported <lua> script in '%transfiletriggerin'
```

But I thought that should be fixed with the new `rpm-ostree`.

**Comment by cgwalters** [comment]
> But I thought that should be fixed with the new rpm-ostree.

I think we want to fast-track it into coreos-assembler to fix that actually.

**Comment by dustymabe** [comment]
> I think we want to fast-track it into coreos-assembler to fix that actually.

yeah we did that already (yesterday). New info: https://github.com/coreos/rpm-ostree/issues/3487

**Comment by dustymabe** [comment]
Considering https://github.com/coreos/rpm-ostree/issues/3487 I dropped the second commit from this PR.

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
