### PR TITLE
Add scripts to verify BZ1980679

### PR DESCRIPTION
**Pull request by HuijingHei**
This PR is to add scripts to verify https://bugzilla.redhat.com/show_bug.cgi?id=1980679:

1. config.ign to include remote.ign
2. Verify kernel arg and exists /etc/testfile

### CODE REVIEW

**Comment by dustymabe** [comment]
this shouldn't be passing CI because https://raw.githubusercontent.com/coreos/fedora-coreos-config/testing-devel/tests/kola/ignition/remote/remote.ign doesn't exist yet (won't exist until https://github.com/coreos/fedora-coreos-config/pull/1227) is merged.

What I notice from the CI run is that the test isn't running, hence why CI is passing. I suspect there is something wrong with this line:

```
# kola: { "platforms": "! qemu-unpriv", "tags": "needs-internet" }
```

**Comment by saqibali-2k** [comment]
> this shouldn't be passing CI because https://raw.githubusercontent.com/coreos/fedora-coreos-config/testing-devel/tests/kola/ignition/remote/remote.ign doesn't exist yet (won't exist until #1227) is merged.
> 
> What I notice from the CI run is that the test isn't running, hence why CI is passing. I suspect there is something wrong with this line:
> 
> ```
> # kola: { "platforms": "! qemu-unpriv", "tags": "needs-internet" }
> ```

The ` "platforms": "! qemu-unpriv"` puts an exclusion on qemu, is that what is messing with CI? Adding the same tag locally and running on aws with `./cosa kola run -p=aws --aws-credentials-file=./aws_credentials` seems to run the test.

**Comment by dustymabe** [comment]
obvious question incoming: is there good reason to not test this on qemu?

**Comment by saqibali-2k** [comment]
> obvious question incoming: is there good reason to not test this on qemu?

Hmm not sure, I think Huijing left a comment in the previous [PR](https://github.com/coreos/coreos-assembler/pull/2446/files). Quoting: `qemu-unpriv machines cannot communicate to network`. I think she will probably expand it on tomorrow.

**Comment by HuijingHei** [comment]
Thanks @dustymabe and @saqibali-2k
My branch has something uncontrolled, so I del this and create another PR https://github.com/coreos/fedora-coreos-config/pull/1231

**Comment by HuijingHei** [comment]
Duplicate of #1232

**Pull request closed without merging**
