### PR TITLE
Add "/etc/multipath.conf" to the Initramfs

### PR DESCRIPTION
**Pull request by nikita-dubrovskii**

### CODE REVIEW

**Comment by nikita-dubrovskii** [comment]
This PR helps with [https://github.com/coreos/fedora-coreos-config/issues/430](url)

**Review by darkmuggle — CHANGES_REQUESTED** [review]
IMO, we really do not want to have a default `multipath.conf` present. I've commented in #430 but we are waiting an updated Dracut module that supports `rd.multipath=default` that will provide for this feature without enabling it for everyone. 

Per https://github.com/dracutdevs/dracut/blob/master/modules.d/90multipath/multipathd.service#L8-L12 this change would effectively make Multipath on by default since it checks for an `/etc/multipath.conf`  and will run unless there is "off" karg.

There are some good reasons why people may not want it to be on by default.

**Comment by darkmuggle** [comment]
@nikita-dubrovskii when the bits land, would you be willing to help with the testing on s390x? And most importantly, thank you for taking a stab at this problem.

**Comment by nikita-dubrovskii** [comment]
> @nikita-dubrovskii when the bits land, would you be willing to help with the testing on s390x? And most importantly, thank you for taking a stab at this problem.

sure!

**Pull request closed without merging**
