### PR TITLE
[rawhide] manifest.yaml: start tracking f35

### PR DESCRIPTION
**Pull request by jlebon**
Rawhide is now f35.

### CODE REVIEW

**Comment by jlebon** [comment]
Ahh interesting.

```
Updating metadata for 'fedora-rawhide'...done

error: Updating rpm-md repo 'fedora-rawhide': Failed to download gpg key for repo 'fedora-rawhide': Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-x86_64 [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-x86_64]

script returned exit code 1
```

But hmm, the latest fedora-gpg-keys does have the f35 key:

```
$ rpm -ql fedora-gpg-keys | grep 35
/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-aarch64
/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-armhfp
/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-ppc64le
/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-s390x
/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-x86_64
```

Hmm, I bet this is Quay.io caching an older version.

**Comment by jlebon** [comment]
Yup, indeed:

```
[coreos-assembler]$ rpm -q fedora-gpg-keys
fedora-gpg-keys-33-1.noarch
[coreos-assembler]$ rpm -ql fedora-gpg-keys | grep 35 || echo "not found"
not found
```

Edit: https://github.com/coreos/coreos-assembler/pull/2047

**Review by lucab — APPROVED** [review]

**Comment by jlebon** [comment]
OK, interesting. Hitting lots of SELinux denials there:

```
Feb 19 19:43:17 fedora audit[1]: AVC avc:  denied  { watch } for  pid=1 comm="systemd" path="/run/systemd/resolve/resolv.conf" dev="tmpfs" ino=1445 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=0

Feb 19 19:43:17 fedora audit[1]: AVC avc:  denied  { watch } for  pid=1 comm="systemd" path="/run/systemd/resolve/resolv.conf" dev="tmpfs" ino=1445 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=0

Feb 19 19:43:18 qemu0 audit[1]: AVC avc:  denied  { watch } for  pid=1 comm="systemd" path="/run/systemd/resolve/resolv.conf" dev="tmpfs" ino=1500 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=0

Feb 19 19:43:18 qemu0 audit[1]: AVC avc:  denied  { watch } for  pid=1 comm="systemd" path="/run/systemd/resolve/resolv.conf" dev="tmpfs" ino=1505 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=0

Feb 19 19:43:18 qemu0 audit[934]: AVC avc:  denied  { watch } for  pid=934 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1439 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0

Feb 19 19:43:19 qemu0 audit[938]: AVC avc:  denied  { watch } for  pid=938 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1439 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
```

Hmm, all those seem like they should be allowed. /cc @WOnder93

**Comment by WOnder93** [comment]
@zpytela ^^

The second set seems to be a mislabeled file:
```
$ matchpathcon /run/agetty.reload
/run/agetty.reload      system_u:object_r:getty_var_run_t:s0
```
getty_t itself has a file transition rule to ensure the correct label - could it have been created by a different process?

**Comment by zpytela** [comment]
For the first set, I've just created a PR to address:
https://github.com/fedora-selinux/selinux-policy/pull/606

**Comment by jlebon** [comment]
> getty_t itself has a file transition rule to ensure the correct label - could it have been created by a different process?

Did some digging on this: `/run/agetty.reload` is a stamp file which agetty processes add a watch inotify on. Then when a service does `agetty --reload`, it touches that file, triggering the inotify and causing agetty instances to reload their prompts. What's interesting is that if agetty is started *before* that file is created, then it creates the file with the correct context. But if the file is first created via `agetty --reload`, the wrong context is used:

```
[root@cosa-devsh ~]# rm /run/agetty.reload
[root@cosa-devsh ~]# systemctl restart serial-getty@ttyS0.service
[root@cosa-devsh ~]# ls -lZ /run/agetty.reload
-rw-------. 1 root root system_u:object_r:getty_var_run_t:s0 0 Feb 22 22:11 /run/agetty.reload
[root@cosa-devsh ~]# systemctl stop serial-getty@ttyS0.service
[root@cosa-devsh ~]# rm /run/agetty.reload
[root@cosa-devsh ~]# agetty --reload
[root@cosa-devsh ~]# ls -lZ /run/agetty.reload
-rw-------. 1 root root unconfined_u:object_r:var_run_t:s0 0 Feb 22 22:10 /run/agetty.reload
```

In this case, it's [CLHM](https://github.com/coreos/console-login-helper-messages) calling `agetty --reload` early on.

Hmm I think the issue is that when CLHM (or a user) runs `agetty --reload`, it's not running as `getty_t`, so the transition rule doesn't kick in. I think we need something like this:

```diff
diff --git a/policy/modules/system/getty.te b/policy/modules/system/getty.te
index 03748d1e2..0a496bf31 100644
--- a/policy/modules/system/getty.te
+++ b/policy/modules/system/getty.te
@@ -9,6 +9,7 @@ type getty_t;
 type getty_exec_t;
 init_domain(getty_t, getty_exec_t)
 init_system_domain(getty_t, getty_exec_t)
+application_domain(getty_t, getty_exec_t)
 domain_interactive_fd(getty_t)

 type getty_etc_t;
```

?

**Comment by jlebon** [comment]
> I think we need something like this:

OK nope, that doesn't work.
I do think this statement is correct though:

> Hmm I think the issue is that when CLHM (or a user) runs `agetty --reload`, it's not running as `getty_t`, so the transition rule doesn't kick in.

In the patch above, I was trying to mimic the setup we have with `rpm-ostree` where even if unconfined users run it, it still transitions to `install_t`.

Anyway, filed this as https://bugzilla.redhat.com/show_bug.cgi?id=1932053.

I think we can work around this for now by just touching `/run/agetty.reload` before switchroot.

> For the first set, I've just created a PR to address:
> fedora-selinux/selinux-policy#606

Thanks @zpytela! Could we get another rawhide build with that?

**Comment by zpytela** [comment]
> Thanks @zpytela! Could we get another rawhide build with that?

I am about to create a f34 build soon, just a few more commits; f35 one will be afterwards.

**Comment by jlebon** [comment]
OK cool, looks like the workaround is working! So we're just down to the systemd-resolved denials now.

**Comment by jlebon** [comment]
Looks like it's in f35 now. Retriggered CI!

**Comment by jlebon** [comment]
OK, progress! The old AVCs are gone, but now we're hitting `fowner` AVCs:

```
[2021-02-25T16:18:01.036Z] Feb 25 16:17:49 qemu0 audit[783]: AVC avc:  denied  { fowner } for  pid=783 comm="systemd-hwdb" capability=3  scontext=system_u:system_r:systemd_hwdb_t:s0 tcontext=system_u:system_r:systemd_hwdb_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:52 qemu0 audit[830]: AVC avc:  denied  { fowner } for  pid=830 comm="ldconfig" capability=3  scontext=system_u:system_r:ldconfig_t:s0 tcontext=system_u:system_r:ldconfig_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[874]: AVC avc:  denied  { fowner } for  pid=874 comm="chgrp" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[876]: AVC avc:  denied  { fowner } for  pid=876 comm="chmod" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[877]: AVC avc:  denied  { fowner } for  pid=877 comm="chgrp" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[878]: AVC avc:  denied  { fowner } for  pid=878 comm="chmod" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[879]: AVC avc:  denied  { fowner } for  pid=879 comm="chmod" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[881]: AVC avc:  denied  { fowner } for  pid=881 comm="chmod" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:53 qemu0 audit[870]: AVC avc:  denied  { getattr } for  pid=870 comm="sssd" name="/" dev="tmpfs" ino=1 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:54 qemu0 audit[895]: AVC avc:  denied  { fowner } for  pid=895 comm="chgrp" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:54 qemu0 audit[896]: AVC avc:  denied  { fowner } for  pid=896 comm="chmod" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0

[2021-02-25T16:18:01.036Z] Feb 25 16:17:54 qemu0 audit[897]: AVC avc:  denied  { fowner } for  pid=897 comm="chmod" capability=3  scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:sshd_keygen_t:s0 tclass=capability permissive=0
```

Anyway, I think what I'll do now is add support in cosa for allowing these failures via `kola-denylist.yaml`.

**Comment by jlebon** [comment]
Looks like a bunch of tests are failing. We'll need to dig into those, but let's merge this because even if it doesn't pass tests currently, we want the rawhide stream to be building f35, not f34 anymore.

**Pull request merged**
