### PR TITLE
[testing] tree: promote changes from next at b94dc2e657c57bc2208474c119c4869f91…

### PR DESCRIPTION
**Pull request by ravanelli**
…61cafa

### CODE REVIEW

**Comment by dustymabe** [comment]
mostly LGTM - we need to add one more commit like we did for the `next` stream (see 74cb357)

**Review by dustymabe — CHANGES_REQUESTED** [review]
Move manifest.yaml to 36

**Review by dustymabe — DISMISSED** [review]
LGTM

**Review by dustymabe — DISMISSED** [review]
LGTM

**Comment by dustymabe** [comment]
CI failed with:

```
  Problem: package vim-common-2:8.2.4621-1.fc36.x86_64 requires vim-data = 2:8.2.4621-1.fc36, but none of the providers can be installed
   - cannot install both vim-data-2:8.2.4621-1.fc36.noarch and vim-data-2:8.2.4804-1.fc36.noarch
```

We [fast-tracked](https://github.com/coreos/fedora-coreos-config/commit/e4665ce7f8fde83eefdf7e7a21d980009e7d11e8) a vim package that got unpushed and was obsoleted by a [newer update](https://bodhi.fedoraproject.org/updates/FEDORA-2022-0f5352c759).

**Comment by dustymabe** [comment]
Let's cherry pick the commit from https://github.com/coreos/fedora-coreos-config/pull/1722 when that lands.

Pulling that in will also mean that anyone that had layered a vim subpackage won't have an issue. 

This means the `testing` that we will ship isn't exactly the same as the `next` we shipped today but I think that's OK for a package like `vim`.

**Comment by dustymabe** [comment]
> Let's cherry pick the commit from #1722 when that lands.

Done. CI should pass now (as soon as the new update that just ran hits the mirrors).

**Review by bgilbert — APPROVED** [review]
LGTM

**Pull request merged**
