### PR TITLE
manifest: add fedora-repos-ostree

### PR DESCRIPTION
**Pull request by jlebon**
The subpackage has been created now, so we can start shipping it.

### CODE REVIEW

**Comment by jlebon** [comment]
Though actually... it's only been built for f30 right now. So this is pending on either migrating FCOS to f30, or getting it built in f29.

**Comment by dustymabe** [comment]
yep. we should definitely add it to the silverblue configs too and stop creating the remote using lorax templates

**Comment by sinnykumari** [comment]
Will it be useful to have fedora-repos-ostree available for F29 as well?  Mostly thinking for Silverblue users who would like to upgrade from F29 to F30. They can just install the package fedora-repos-ostree on F29 and can use `rpm-ostree rebase fedora:fedora/30/x86_64/silverblue`

**Comment by dustymabe** [comment]
> Will it be useful to have fedora-repos-ostree available for F29 as well? Mostly thinking for Silverblue users who would like to upgrade from F29 to F30.

I think that would be useful. It would enable us to get those users to use the correct config. They can switch to it when they do the rebase to f30.

**Comment by sinnykumari** [comment]
PR to have fedora-repos-ostree sub-package in F29- https://src.fedoraproject.org/rpms/fedora-repos/pull-request/33

**Comment by sinnykumari** [comment]
Latest f29-updates [fedora-repos-29-5](https://koji.fedoraproject.org/koji/buildinfo?buildID=1238947) contains fedora-repos-ostree. LGTM to get merged now.

**Review by sinnykumari — APPROVED** [review]

**Comment by sinnykumari** [comment]
We have moved to [F30 based content](https://github.com/coreos/fedora-coreos-config/commit/6ca5469cbfd871536f71903d6307b6bf95a40687) , should be merge this now?

**Comment by jlebon** [comment]
Yes we should, thanks Sinny!

**Pull request merged**
