### PR TITLE
overlay.d: Move sshd_config.d configs to 15fcos

### PR DESCRIPTION
**Pull request by travier**
Keep all sshd_config.d config snippets in 15fcos (FCOS specific) as
OpenSSH version in RHCOS is not capable of handling them yet.

In this case, RHCOS also does not want to read keys added by afterburn.

This PR also include a README update extracted from https://github.com/coreos/fedora-coreos-config/pull/461 that is not merge ready.

### CODE REVIEW

**Comment by bgilbert** [comment]
For what it's worth, older OpenSSH will just ignore the fragment.

**Review by jamescassell — APPROVED** [review]

**Comment by cgwalters** [comment]
> For what it's worth, older OpenSSH will just ignore the fragment.

Ah, I see.  It is still a bit deceptive to ship it and have it not take effect though, so probably better to remove it for now to avoid confusion?

**Comment by lucab** [comment]
I agree it's better to not forward the fragment at all to RCHOS (where it is unsupported), because empirically this exact point already caused confusion when discussing this topic internally among us yesterday.

**Review by bgilbert — APPROVED** [review]

**Comment by travier** [comment]
How do I retry the CI checks here?

**Comment by bgilbert** [comment]
@travier If you click the Details link and log into Jenkins, there's a rerun button in the top bar.

**Comment by lucab** [comment]
I rerun this manually, I think @travier is missing permissions to access CI.

**Pull request merged**
