### PR TITLE
overlay/ignition-ostree: Hook up to ignition-diskful-subsequent

### PR DESCRIPTION
**Pull request by cgwalters**
Per review, rather than having a custom generator.  The code becomes
simpler.  This makes use of https://github.com/coreos/ignition-dracut/pull/151

### CODE REVIEW

**Comment by cgwalters** [comment]
Depends on https://github.com/coreos/ignition-dracut/pull/151

**Comment by jlebon** [comment]
https://src.fedoraproject.org/rpms/ignition/pull-request/50

**Comment by dustymabe** [comment]
this should be in now with #278

**Comment by dustymabe** [comment]
tests failed. maybe rebase this PR and let's run them again?

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by cgwalters** [comment]
Hm, we could also remove live-generator I think and ship static units keyed off `diskful` and `diskful-subsequent` possibly too.

**Comment by cgwalters** [comment]
But eh, might as well be incremental.

**Comment by jlebon** [comment]
> Hm, we could also remove live-generator I think and ship static units keyed off `diskful` and `diskful-subsequent` possibly too.

Hmm, though those are meant to run when we are live, so it'd require a new e.g. `ignition-diskless.target` and `ignition-diskless-subsequent.target`. Though those targets would be misleading I think in a live PXE context. And anyway, the logic there is the same regardless of whether Ignition runs.

**Pull request merged**
