### PR TITLE
[testing] overrides: pin podman-4.7.2-1.fc39

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @jbtrystram via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Review by jlebon — APPROVED** [review]
I think we need one for `next` too.

**Comment by jlebon** [comment]
Sorry, I got confused here.

We're cutting a release this week, so we'll repromote from testing-devel as part of that (https://github.com/coreos/fedora-coreos-streams/issues/825).

So this should be opened against testing-devel and next-devel instead.

**Comment by dustymabe** [comment]
> So this should be opened against testing-devel and next-devel instead.

yes. I think what we need to do is try to determine if the reported issues (reported against silverblue) are an issue for FCOS too and then open a tracker issue and pin. I think the issues may have something to do with upgrading systems, which we don't have great CI coverage for. 

Hence our CI passes fine, but that doesn't mean the new podman is without regressions.

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2753
- https://github.com/coreos/fedora-coreos-config/pull/2754

**Pull request closed without merging**
