### PR TITLE
README: describe process for adding package overrides

### PR DESCRIPTION
**Pull request by jlebon**
That way we can link folks to there if they want to add overrides.

### CODE REVIEW

**Comment by jlebon** [comment]
Works on top of https://github.com/coreos/fedora-coreos-config/pull/227.

**Review by miabbott — APPROVED** [review]
:+1:

**Review by dustymabe — APPROVED** [review]
LGTM, when #227 merges

**Comment by lucab** [comment]
@jlebon if you rebase this one, it should be good to merge.

**Comment by jlebon** [comment]
> @jlebon if you rebase this one, it should be good to merge.

Thanks, rebased! I had forgotten this was still pending.

**Pull request merged**
