### PR TITLE
[next-devel] overrides: fast-track libnvme-1.6-2.fc39

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @dustymabe via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Comment by dustymabe** [comment]
This package is in the latest F39 RC composes.

**Review by yasminvalim — APPROVED** [review]

**Review by marmijo — APPROVED** [review]

**Comment by jlebon** [comment]
OOC, how are you tracking this stuff? Are you just following tickets like https://pagure.io/releng/issue/11742 or do you do a repoquery of some kind? Would be good to formalize this stuff.

**Comment by dustymabe** [comment]
yeah I was following https://pagure.io/releng/issue/11742 and only did this one because I was thinking for a moment there we were going to be "Go" today and wanted to get a head start.

At the end of the day we can just use the repo at `https://kojipkgs.fedoraproject.org/compose/39/latest-Fedora-39/compose/Everything/$basearch/os/` though.

**Comment by jlebon** [comment]
OK, let's take this to https://github.com/coreos/fedora-coreos-tracker/issues/1602.

**Pull request merged**
