### PR TITLE
ci: buildprep from latest testing-devel

### PR DESCRIPTION
**Pull request by jlebon**
That way if a PR adds a package, we'll print the pkg diff.

### CODE REVIEW

**Comment by jlebon** [comment]
> ostree diff commit from: eb9c3da15432707382294fca7e1a2c80aa81768ec5ce14aedcc181491a00b897
> ostree diff commit to:   c12b04a3eff9495d52f65a40cdc8581028988e1170fce08160f41080061fb3fc

Understandably, there's no diff in this PR, but it's comparing to the previous commit, which is the important part.

**Review by cgwalters — APPROVED** [review]

**Comment by ajeddeloh** [comment]
This LGTM but are there plans to make this more visible from GH? It's somewhat buried atm, which I suppose is fine since it only applies to a certain set of PRs. OTOH more visibility is better.

**Comment by jlebon** [comment]
> This LGTM but are there plans to make this more visible from GH?

There aren't plans *not to* ;)

**Comment by jlebon** [comment]
I made it print the pkgdiff as a separate stage at least so it's easier to access. :arrow_up:

**Review by ajeddeloh — APPROVED** [review]
:+1: to separate stage for visibility.

**Comment by ajeddeloh** [comment]
CI is failing for unrelated reasons. Is there anything blocking this?

**Comment by jlebon** [comment]
No I think the CI failure is related, I'm just not sure how yet.

**Comment by jlebon** [comment]
OK, let's try this again on top of the new CI!

**Pull request merged**
