### PR TITLE
[stable] tree: promote changes from testing at 8904efe05d19fce4f8930454a42c3b491a2fb450

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @travier in https://github.com/coreos/fedora-coreos-streams/issues/337.

### CODE REVIEW

**Comment by travier** [comment]
I don't know if the `.cci.jenkinsfile` change is expected here.

**Review by travier — APPROVED** [review]

**Comment by dustymabe** [comment]
> I don't know if the `.cci.jenkinsfile` change is expected here.

I think it is because it was put in place just to get the last build out the door (failing kola test or something in COSA that only applied to newer FCOS).

**Comment by dustymabe** [comment]
```
$ git diff upstreamtesting
diff --git a/manifest.yaml b/manifest.yaml
index f03556f..261e9dc 100644
--- a/manifest.yaml
+++ b/manifest.yaml
@@ -1,4 +1,4 @@
-ref: fedora/${basearch}/coreos/testing
+ref: fedora/${basearch}/coreos/stable
 include: manifests/fedora-coreos.yaml
 
 releasever: "34"
@@ -6,10 +6,10 @@ releasever: "34"
 rojig:
   license: MIT
   name: fedora-coreos
-  summary: Fedora CoreOS testing
+  summary: Fedora CoreOS stable
 
 repos:
   - fedora-coreos-pool
 
 add-commit-metadata:
-  fedora-coreos.stream: testing
+  fedora-coreos.stream: stable
```

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
