### PR TITLE
[next] tree: promote changes from testing-devel at 262ea8b2b031a81a3cb379a93803ebdc2d407709

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @jlebon in https://github.com/coreos/fedora-coreos-streams/issues/993.

### CODE REVIEW

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
hmm. there still isn't something right with the submodule promotion:

```
git rev-parse HEAD^{commit} # timeout=10
git config core.sparsecheckout # timeout=10
git checkout -f 00ef10a908f2c860aeda869b45dfedd6e58a67d2 # timeout=10
git remote # timeout=10
git submodule init # timeout=10
Could not perform submodule update
```

**Comment by jlebon** [comment]
Let's try https://github.com/coreos/fedora-coreos-streams/pull/997.

**Pull request closed without merging**
