### PR TITLE
Make manifests dir for included manifests.

### PR DESCRIPTION
**Pull request by dustymabe**
The toplevel directory in this repo is getting quite polluted.
Let's move all sub-manifests into a manifests subdirectory.

### CODE REVIEW

**Comment by jlebon** [comment]
Seems fine, though this will require adapting RHCOS as well to point to the new paths it includes.

**Comment by dustymabe** [comment]
> Seems fine, though this will require adapting RHCOS as well to point to the new paths it includes.

yep, if this passes review. I'll apply the changes downstream.

**Review by jlebon — APPROVED** [review]
SGTM! I think it does clean up things nicely.
Will leave it open for a bit.

**Comment by dustymabe** [comment]
> SGTM! I think it does clean up things nicely.

thanks! It would be nice to also throw the repos in a subdir. Would that require changes to rpm-ostree ?

**Comment by cgwalters** [comment]
> Seems fine, though this will require adapting RHCOS as well to point to the new paths it includes.

Yes, though since as a git submodule it pins the commit, that's not necessary to do *immediately* after this.  

It doesn't hurt though either of course!

**Comment by jlebon** [comment]
I'm going to guess tests failed because of https://github.com/coreos/coreos-assembler/pull/786#issuecomment-548136360. Now that https://github.com/coreos/coreos-assembler/pull/882 is merged, I restarted tests to confirm this.

**Comment by dustymabe** [comment]
FYI this seems to pass in local tests:

<details>

```
$ 
[dustymabe@media fedora]$ cosa kola
COREOS_ASSEMBLER_GIT=/var/b/shared/code/github.com/coreos/coreos-assembler/
COREOS_ASSEMBLER_CONFIG_GIT=/var/b/shared/code/github.com/coreos/fedora-coreos-config/
+ podman run --rm -ti --security-opt label=disable --privileged --uidmap=1000:0:1 --uidmap=0:1:1000 --uidmap 1001:1001:64536 -v /var/b/shared/assembler/fedora:/srv/ --device /dev/kvm --deva
⚠️  Skipping kola test pattern "fcos.python":
⚠️  https://github.com/coreos/mantle/issues/1103
qemu path: builds/31.20191030.dev.2/x86_64/fedora-coreos-31.20191030.dev.2-qemu.x86_64.qcow2
Using ignition version 3.0.0
kola -b fcos -p qemu-unpriv --qemu-image builds/31.20191030.dev.2/x86_64/fedora-coreos-31.20191030.dev.2-qemu.x86_64.qcow2 --output-dir tmp/kola run --blacklist-test fcos.python
=== RUN   podman.workflow
=== RUN   podman.base
=== RUN   coreos.ignition.resource.remote
=== RUN   rpmostree.status
=== RUN   rhcos.selinux.boolean.persist
=== RUN   systemd.sysusers.gshadow
=== RUN   rpmostree.upgrade-rollback
=== RUN   ostree.remote
=== RUN   podman.network-single
=== RUN   coreos.ignition.once
=== RUN   fcos.basic
=== RUN   coreos.auth.verify
=== RUN   rpmostree.install-uninstall
=== RUN   coreos.ignition.sethostname
=== RUN   ostree.hotfix
=== RUN   coreos.ignition.v2.users
=== RUN   coreos.ignition.groups
=== RUN   coreos.selinux.boolean
=== RUN   coreos.selinux.enforce
=== RUN   ostree.unlock
=== RUN   podman.workflow/run
=== RUN   podman.workflow/exec
=== RUN   podman.workflow/stop
=== RUN   podman.workflow/remove
=== RUN   podman.workflow/delete
--- PASS: podman.workflow (38.96s)
    --- PASS: podman.workflow/run (10.58s)
            cluster.go:122: Trying to pull docker.io/library/nginx...
            cluster.go:122: Getting image source signatures
            cluster.go:122: Copying blob sha256:5b07f4e08ad08c4b6d4bffa634b7e7813a3348ad472b155ac40804871fb6959b
            cluster.go:122: Copying blob sha256:abc291867bca9d5143a0e40a8ddfb149fff4cd48965fd7597f1a248b524ca07d
            cluster.go:122: Copying blob sha256:8d691f585fa8cec0eba196be460cfaffd69939782d6162986c3e0c5225d54f02
            cluster.go:122: Copying config sha256:540a289bab6cb1bf880086a9b803cf0c4cefe38cbb5cdefa199b69614525199f
            cluster.go:122: Writing manifest to image destination
            cluster.go:122: Storing signatures
    --- PASS: podman.workflow/exec (0.34s)
    --- PASS: podman.workflow/stop (0.76s)
    --- PASS: podman.workflow/remove (0.54s)
    --- PASS: podman.workflow/delete (0.75s)
            cluster.go:122: grep: docker.io/library/nginx:latest: No such file or directory
            cluster.go:122: bash: line 1: Deleted:: command not found
--- PASS: coreos.auth.verify (25.41s)
=== RUN   ostree.unlock/unlock
=== RUN   ostree.unlock/install
=== RUN   ostree.unlock/uninstall
=== RUN   ostree.unlock/discard
--- PASS: ostree.unlock (46.90s)
    --- PASS: ostree.unlock/unlock (0.45s)
    --- PASS: ostree.unlock/install (0.83s)
    --- PASS: ostree.unlock/uninstall (0.50s)
    --- PASS: ostree.unlock/discard (19.41s)
--- PASS: coreos.selinux.enforce (45.27s)
--- PASS: coreos.selinux.boolean (44.37s)
--- PASS: coreos.ignition.groups (25.99s)
--- PASS: coreos.ignition.v2.users (26.50s)
=== RUN   ostree.hotfix/unlock
=== RUN   ostree.hotfix/install
=== RUN   ostree.hotfix/uninstall
=== RUN   ostree.hotfix/persist
=== RUN   ostree.hotfix/rollback
--- PASS: ostree.hotfix (70.45s)
    --- PASS: ostree.hotfix/unlock (5.07s)
    --- PASS: ostree.hotfix/install (0.75s)
    --- PASS: ostree.hotfix/uninstall (0.47s)
    --- PASS: ostree.hotfix/persist (19.00s)
    --- PASS: ostree.hotfix/rollback (19.45s)
--- PASS: coreos.ignition.sethostname (24.80s)
=== RUN   rpmostree.install-uninstall/install
=== RUN   rpmostree.install-uninstall/uninstall
--- PASS: rpmostree.install-uninstall (106.01s)
    --- PASS: rpmostree.install-uninstall/install (56.84s)
    --- PASS: rpmostree.install-uninstall/uninstall (23.64s)
--- PASS: coreos.ignition.once (44.05s)
=== RUN   fcos.basic/MachineID
=== RUN   fcos.basic/PortSSH
=== RUN   fcos.basic/DbusPerms
=== RUN   fcos.basic/NetworkScripts
=== RUN   fcos.basic/ServicesActive
=== RUN   fcos.basic/ReadOnly
=== RUN   fcos.basic/Useradd
--- PASS: fcos.basic (27.58s)
    --- PASS: fcos.basic/MachineID (0.14s)
    --- PASS: fcos.basic/PortSSH (0.15s)
    --- PASS: fcos.basic/DbusPerms (0.30s)
    --- PASS: fcos.basic/NetworkScripts (0.15s)
    --- PASS: fcos.basic/ServicesActive (0.17s)
    --- PASS: fcos.basic/ReadOnly (0.14s)
    --- PASS: fcos.basic/Useradd (0.41s)
--- PASS: rpmostree.status (25.86s)
--- PASS: systemd.sysusers.gshadow (25.88s)
--- PASS: rhcos.selinux.boolean.persist (46.06s)
--- PASS: coreos.ignition.resource.remote (25.17s)
--- PASS: podman.network-single (199.38s)
        cluster.go:122: STEP 1: FROM scratch
        cluster.go:122: STEP 2: COPY . /
        cluster.go:122: STEP 3: COMMIT localhost/ping
        cluster.go:122: Getting image source signatures
        cluster.go:122: Copying blob sha256:fe59491251ea58c5751d531bf858fa9bbc439783008e5636a3c182c879627abc
        cluster.go:122: Copying config sha256:ef40b52b7e70eaee82178732371d271c8a7edea28b77c8b87e569f4a7b186402
        cluster.go:122: Writing manifest to image destination
        cluster.go:122: Storing signatures
=== RUN   podman.base/info
=== RUN   podman.base/resources
--- PASS: podman.base (71.83s)
    --- PASS: podman.base/info (0.44s)
    --- PASS: podman.base/resources (46.73s)
            cluster.go:122: STEP 1: FROM scratch
            cluster.go:122: STEP 2: COPY . /
            cluster.go:122: STEP 3: COMMIT localhost/echo
            cluster.go:122: Getting image source signatures
            cluster.go:122: Copying blob sha256:fb8d29d8718b74ceddfde19903151c5ef9f3f82034a73ecfc4505bef230ad427
            cluster.go:122: Copying config sha256:5c3bbeb0244e81f3fc69fc4d24d6d4cb6acc61a6ce35fc6d64b72ddffc3d256c
            cluster.go:122: Writing manifest to image destination
            cluster.go:122: Storing signatures
            cluster.go:122: Your kernel does not support Block I/O weight or the cgroup is not mounted. Weight discarded.
=== RUN   rpmostree.upgrade-rollback/upgrade
=== RUN   rpmostree.upgrade-rollback/rollback
--- PASS: rpmostree.upgrade-rollback (69.49s)
    --- PASS: rpmostree.upgrade-rollback/upgrade (21.75s)
    --- PASS: rpmostree.upgrade-rollback/rollback (22.28s)
=== RUN   ostree.remote/add
=== RUN   ostree.remote/list
=== RUN   ostree.remote/show-url
=== RUN   ostree.remote/refs
=== RUN   ostree.remote/summary
=== RUN   ostree.remote/delete
--- PASS: ostree.remote (28.94s)
    --- PASS: ostree.remote/add (0.20s)
    --- PASS: ostree.remote/list (0.14s)
    --- PASS: ostree.remote/show-url (0.14s)
    --- PASS: ostree.remote/refs (0.90s)
    --- PASS: ostree.remote/summary (1.81s)
    --- PASS: ostree.remote/delete (0.49s)
PASS, output in tmp/kola
+ rc=0
+ set +x

```

</details>

**Pull request merged**
