### PR TITLE
kola: enable tests with 'appendKernelArgs' on s390x

### PR DESCRIPTION
**Pull request by nikita-dubrovskii**
Requires: https://github.com/coreos/coreos-assembler/pull/3440

### CODE REVIEW

**Comment by dustymabe** [comment]
should be able to also enable `appendFirstBootKernelArgs` tests

**Comment by dustymabe** [comment]
> should be able to also enable `appendFirstBootKernelArgs` tests

and your last upload does just that

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by nikita-dubrovskii** [comment]
Tested on `s390x` :
```
$ cosa kola run --rerun --parallel 8 ext.config.networking.*
⚠️  Skipping kola test pattern "fcos.internet":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
⚠️  Skipping kola test pattern "podman.workflow":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
=== RUN   ext.config.networking.force-persist-ip
=== RUN   ext.config.networking.ifname-karg.everyboot-systemd-link-file
=== RUN   ext.config.networking.mtu-on-bond-kargs
=== RUN   ext.config.networking.bridge-static-via-kargs
=== RUN   ext.config.networking.kargs-rd-net
=== RUN   ext.config.networking.no-default-initramfs-net-propagation.bootif
=== RUN   ext.config.networking.no-persist-ip
=== RUN   ext.config.networking.prefer-ignition-networking
=== RUN   ext.config.networking.ifname-karg.udev-rule-firstboot-propagation
=== RUN   ext.config.networking.mtu-on-bond-ignition
=== RUN   ext.config.networking.rd-net-timeout-carrier
=== RUN   ext.config.networking.team-dhcp-via-ignition
=== RUN   ext.config.networking.nmstate.policy
=== RUN   ext.config.networking.nmstate.state
=== RUN   ext.config.networking.hostname.fallback-hostname
=== RUN   non-exclusive-test-bucket-0
=== RUN   ext.config.networking.nameserver
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.nm-start
--- PASS: ext.config.networking.hostname.fallback-hostname (26.88s)
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.dnsmasq-service
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.nic-naming
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.network-online-service
--- PASS: ext.config.networking.no-default-initramfs-net-propagation.bootif (28.98s)
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.no-default-initramfs-net-propagation.default
--- PASS: ext.config.networking.nameserver (29.27s)
--- PASS: ext.config.networking.team-dhcp-via-ignition (29.61s)
--- PASS: ext.config.networking.mtu-on-bond-ignition (29.69s)
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.tls
--- PASS: ext.config.networking.force-persist-ip (30.73s)
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.nm-dhcp-client
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.default-network-behavior-change
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.resolv.systemd-resolved
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.nm-ifcfg-rh-plugin
--- PASS: non-exclusive-test-bucket-0 (39.95s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.nm-start (1.64s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.dnsmasq-service (0.60s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.nic-naming (0.58s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.network-online-service (0.59s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.no-default-initramfs-net-propagation.default (1.61s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.tls (3.61s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.nm-dhcp-client (0.59s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.default-network-behavior-change (1.64s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.resolv.systemd-resolved (0.61s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.networking.nm-ifcfg-rh-plugin (0.64s)
--- PASS: ext.config.networking.prefer-ignition-networking (28.23s)
--- PASS: ext.config.networking.no-persist-ip (28.48s)
--- PASS: ext.config.networking.bridge-static-via-kargs (29.09s)
--- PASS: ext.config.networking.rd-net-timeout-carrier (33.84s)
--- PASS: ext.config.networking.kargs-rd-net (28.72s)
--- PASS: ext.config.networking.nmstate.state (39.53s)
--- PASS: ext.config.networking.ifname-karg.udev-rule-firstboot-propagation (40.50s)
--- PASS: ext.config.networking.mtu-on-bond-kargs (29.07s)
--- PASS: ext.config.networking.ifname-karg.everyboot-systemd-link-file (40.04s)
--- PASS: ext.config.networking.nmstate.policy (102.01s)
PASS, output in tmp/kola
+ rc=0
+ set +x

```

**Review by jlebon — APPROVED** [review]
LGTM! Thanks for sanity-checking everything still passes. We just promoted content for testing, so this shouldn't run in this week's releases.

**Pull request merged**
