### PR TITLE
base: Drop grub2 fallback script

### PR DESCRIPTION
**Pull request by LorbusChris**
follow up on #36 #37.

~~Hold until we consume rpms from f30 repos!~~

### CODE REVIEW

**Comment by LorbusChris** [comment]
https://github.com/rhboot/grub2/pull/52/files has merged, and with it the files we remove here. Will update this PR.

**Comment by dustymabe** [comment]
@LorbusChris - does this need to be 'updated and merged' or 'closed' ?

**Comment by LorbusChris** [comment]
oh this slipped thru. needs to be updated to:
`rm -v /etc/grub.d/{08_fallback_counting,10_reset_boot_success,12_menu_auto_hide}`

Left the office already, but will do that first thing tomorrow!

**Comment by LorbusChris** [comment]
Best way would be to split the grub.d script snippets out into subackage(s), though. Last I heard the grub team plans on doing that (someday), but until then, let's do this here.

**Comment by dustymabe** [comment]
LGTM - cc @ajeddeloh

**Pull request merged**
