### PR TITLE
ci/find-whitespace: Check for missing empty line at end of file

### PR DESCRIPTION
**Pull request by travier**
overlay.d: Fix missing end of line at the end of file

---

ci/find-whitespace: Check for missing EOL at EOF

Rework the find-whitespace CI script to check more files and also check
for missing end of line at the end of files.

See: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
See: https://stackoverflow.com/questions/4631068/how-do-i-find-files-that-do-not-end-with-a-newline-linefeed

### CODE REVIEW

**Review by jbtrystram — DISMISSED** [review]
LGTM

**Comment by travier** [comment]
I'll improve the script more. Converted to draft.

**Review by jlebon — APPROVED** [review]
Looks sane to me!

**Review by jbtrystram — APPROVED** [review]
LGTM

**Pull request merged**
