### PR TITLE
overrides: fast-track Ignition 2.7.0

### PR DESCRIPTION
**Pull request by arithx**

### CODE REVIEW

**Review by bgilbert — APPROVED** [review]

**Comment by dustymabe** [comment]
CI failed with:

```
Error: Parsing config.ign: unsupported config version

2020-10-15T05:53:55Z cli: Parsing config.ign: unsupported config version
```

**Comment by jlebon** [comment]
> CI failed with:

Yeah, this is expected. It needs https://github.com/coreos/coreos-assembler/pull/1793.

**Comment by sohankunkerkar** [comment]
> > CI failed with:
> 
> Yeah, this is expected. It needs [coreos/coreos-assembler#1793](https://github.com/coreos/coreos-assembler/pull/1793).

This PR has merged so re-kicking CI.

**Review by sohankunkerkar — APPROVED** [review]

**Review by jlebon — COMMENTED** [review]
This needs to also revert #690, right?

**Review by jlebon — APPROVED** [review]
> This needs to also revert #690, right?

Did that!

**Pull request merged**
