### PR TITLE
[next] tree: promote changes from testing-devel at 351528ebe9893671ed414fbcf923da42dfa96fd4

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by sinnykumari** [comment]
Since we are already releasing testing stream based on F32, this PR is promoting changes in next from testing-devel. Let me know we need to do something differently here :)

**Comment by dustymabe** [comment]
> Since we are already releasing testing stream based on F32, this PR is promoting changes in next from testing-devel. Let me know we need to do something differently here :)

nope, that's right!

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
Let's use #475 to pick up the new kernel/microcode_ctl for the recent CVE (see #473).

**Comment by sinnykumari** [comment]
closing in favor of https://github.com/coreos/fedora-coreos-config/pull/475

**Pull request closed without merging**
