### PR TITLE
[next] tree: promote changes from next-devel at 2bc9a5b

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Review by sohankunkerkar — APPROVED** [review]
LGTM

**Comment by sohankunkerkar** [comment]
I was wondering if you need to revert this change(https://github.com/coreos/fedora-coreos-config/commit/f2152e9cc303a09cfaca025b5b94342de679e3cd)

**Comment by sohankunkerkar** [comment]
related to: https://github.com/coreos/fedora-coreos-config/pull/581

**Comment by darkmuggle** [comment]
I don't see anything obvious, so LGTM other than @sohankunkerkar's question.

**Comment by dustymabe** [comment]
> I was wondering if you need to revert this change([f2152e9](https://github.com/coreos/fedora-coreos-config/commit/f2152e9cc303a09cfaca025b5b94342de679e3cd))

nope. Those are all graduated so we're good.

**Pull request merged**
