### PR TITLE
Revert "overlay.d/09misc: Fix mode for some files in /etc"

### PR DESCRIPTION
**Pull request by travier**
This is now safe to revert as this has been included in a testing
release with a barrier and will thus also be in the next stable release:
https://github.com/coreos/fedora-coreos-streams/pull/328

This reverts commit 73145e08b856ec59906e2256e200d626eba75097.

### CODE REVIEW

**Comment by travier** [comment]
Marking hold has I have not yet fully checked the status of the latest releases, etc.

**Review by jlebon — APPROVED** [review]

**Comment by dustymabe** [comment]
@travier - what's the status here?

**Comment by travier** [comment]
I have not yet had the time to check if everything is good now.

**Comment by travier** [comment]
I have now checked the latest releases and all my FCOS systems and they are in order so I'd say we're good to go here.

**Review by jlebon — APPROVED** [review]

**Pull request merged**
