### PR TITLE
[testing-devel] lockfiles: drop graduated overrides 🎓

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by remove-graduated-overrides [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/remove-graduated-overrides.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/remove-graduated-overrides.yml)).

### CODE REVIEW

**Review by bgilbert — DISMISSED** [review]

**Comment by bgilbert** [comment]
CI failing with:

```
error: Packages not found: nmstate
```

Do we have to do something special to tag nmstate into the pool?

**Comment by jlebon** [comment]
> CI failing with:
> 
> ```
> error: Packages not found: nmstate
> ```
> 
> Do we have to do something special to tag nmstate into the pool?

Nothing special. The issue is that nmstate isn't in the base lockfiles yet so dropping it from the overrides lockfile here means it's now completely unlocked and `cosa fetch --strict` doesn't like that. Ideally https://github.com/coreos/fedora-coreos-config/pull/2269 should've added nmstate to the base lockfiles. This will be fixed by the next bump-lockfile run.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by bgilbert** [comment]
> Ideally #2269 should've added nmstate to the base lockfiles.

Oof.  It originally did, and I thought it still did at merge time, but apparently that was dropped from the PR and I didn't notice.  Apologies for the noise.

**Pull request merged**
