### PR TITLE
[branched] Ignore json-glib broken symlink and unpin

### PR DESCRIPTION
**Pull request by travier**
See: https://bugzilla.redhat.com/show_bug.cgi?id=2297094

---

Will have to open the same for Rawhide as well.

### CODE REVIEW

**Review by marmijo — DISMISSED** [review]
LGTM

**Comment by marmijo** [comment]
PR for rawhide: https://github.com/coreos/fedora-coreos-config/pull/3117

**Comment by marmijo** [comment]
This will need a rebase and a quick edit after https://github.com/coreos/fedora-coreos-config/pull/3116 merges.

**Comment by travier** [comment]
Rebased

**Review by jlebon — APPROVED** [review]
Thanks!

**Comment by jlebon** [comment]
The tests/ changes here need to be done against testing-devel. It'll be overwritten by the next sync. Sorry, I missed this.

**Comment by travier** [comment]
https://github.com/coreos/fedora-coreos-config/pull/3129

**Pull request merged**
