### PR TITLE
[next-devel] lockfiles: drop graduated overrides 🎓

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by remove-graduated-overrides [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/remove-graduated-overrides.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/remove-graduated-overrides.yml)).

### CODE REVIEW

**Review by dustymabe — DISMISSED** [review]
LGTM

**Comment by dustymabe** [comment]
This is warning of downgrades. We'll have to wait for the mirrors to catch up. Will periodically run CI until that happens and tests pass.

**Comment by jlebon** [comment]
Hmm, isn't this rather https://github.com/coreos/fedora-coreos-config/pull/1452#issuecomment-1023426078? And... ahh yup, I never circled back on https://github.com/coreos/fedora-coreos-config/pull/1452#issuecomment-1023430724.

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
