### PR TITLE
[stable] overrides: pin rust-zincati-0.0.25-4.fc38

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @dustymabe via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Comment by dustymabe** [comment]
CI failed with:

```
[2023-11-08T02:16:06.105Z] ostree diff commit from: f072777dcbc3b64088b021283a2f719af516171595a8fb88cc17d4dcc87ad995
[2023-11-08T02:16:06.105Z] ostree diff commit to:   b9013a562c22c99f10328939b4641e354821a02a3e7e31601358f33e695098e9
[2023-11-08T02:16:06.105Z] Downgraded:
[2023-11-08T02:16:06.105Z]   zincati 0.0.26-2.fc38 -> 0.0.25-4.fc38
[2023-11-08T02:16:06.105Z] + grep -q Downgraded tmp/diff.txt
[2023-11-08T02:16:06.105Z] + echo 'Downgrade detected. This is likely unintentional. If not, you may safely ignore this error.'
[2023-11-08T02:16:06.105Z] Downgrade detected. This is likely unintentional. If not, you may safely ignore this error.
```

which is the point of this PR so we'll ignore the error.

**Comment by dustymabe** [comment]
I'll cheat and post a review :)

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by jlebon — COMMENTED** [review]
LGTM but before we release this, let's sanity-check that it indeed doesn't hit https://github.com/coreos/fedora-coreos-tracker/issues/1608.

**Pull request merged**
