### PR TITLE
[branched] manifest: bump to f35

### PR DESCRIPTION
**Pull request by jlebon**
Fedora 35 just branched now.

### CODE REVIEW

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
might need to verify our "lists of streams" in various places include `brached`

**Comment by jlebon** [comment]
Hmm fun, getting lots of network related issues. Digging.

**Comment by dustymabe** [comment]
> Hmm fun, getting lots of network related issues. Digging.

Yeah, I left a note, but maybe not in the best place: https://github.com/coreos/fedora-coreos-tracker/issues/884#issuecomment-869996844

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
