### PR TITLE
[rawhide] Switch to deploying via container image

### PR DESCRIPTION
**Pull request by cgwalters**
Because rawhide is a mechanical stream, this won't break anything for production streams.  It will help shake out anything that might be broken by this.

### CODE REVIEW

**Comment by dustymabe** [comment]
I thought we tried to make this change sometime recently and we couldn't for some reason.

If it works then LGTM!

**Comment by dustymabe** [comment]
CI failure is maybe related to https://github.com/coreos/zincati/issues/859 ?

**Comment by cgwalters** [comment]
It needs https://github.com/coreos/zincati/pull/876

**Comment by cgwalters** [comment]
> It needs https://github.com/coreos/zincati/pull/876

Built in https://koji.fedoraproject.org/koji/buildinfo?buildID=2316475

**Comment by dustymabe** [comment]
The most recent CI run has `zincati 0.0.26-2.fc40 -> 0.0.26-3.fc40` but there is one test still failing:

```
[2023-11-07T15:19:11.048Z] Nov 07 15:17:59 qemu0 kola-runext-kernel-replace[2135]: + ostree container encapsulate --repo=/ostree/repo 5cbfdf91992513ff67e9a49d01517d2c7606803679a3c06cff20d3e5d15d9c0b oci:/var/tmp/fcos
[2023-11-07T15:19:11.048Z] Nov 07 15:19:02 qemu0 kola-runext-kernel-replace[2214]: sha256:874d67e623e684fcc4553ba365064cce33fa8f72d1c34b77132e17bde8ca4b92
[2023-11-07T15:19:11.048Z] Nov 07 15:19:02 qemu0 kola-runext-kernel-replace[2135]: + rpm-ostree rebase --experimental ostree-unverified-image:oci:/var/tmp/fcos
[2023-11-07T15:19:11.048Z] Nov 07 15:19:02 qemu0 kola-runext-kernel-replace[2229]: Pulling manifest: ostree-unverified-image:oci:/var/tmp/fcos
[2023-11-07T15:19:11.048Z] Nov 07 15:19:03 qemu0 kola-runext-kernel-replace[2229]: error: Preparing import: Fetching manifest: Target image does not have ostree.bootable label
[2023-11-07T15:19:11.048Z] Nov 07 15:19:03 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
[2023-11-07T15:19:11.048Z] Nov 07 15:19:03 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
[2023-11-07T15:19:11.048Z] Nov 07 15:19:03 qemu0 systemd[1]: kola-runext.service: Consumed 1min 884ms CPU time.
[2023-11-07T15:19:11.048Z] --- FAIL: ext.config.rpm-ostree.kernel-replace (92.52s)
```

**Comment by cgwalters** [comment]
OK split out the test fix into https://github.com/coreos/fedora-coreos-config/pull/2729

**Review by dustymabe — DISMISSED** [review]
This still LGTM, but the GH web UI is complaining about conflicts that will prevent merge.

**Comment by dustymabe** [comment]
ok I think I fixed the merge conflict and rebased on top of latest `rawhide`

**Review by dustymabe — APPROVED** [review]

**Review by jlebon — APPROVED** [review]
LGTM too.

**Comment by cgwalters** [comment]
Thanks!  Let's keep an eye out for fallout.

**Comment by dustymabe** [comment]
🔍 👀

**Pull request merged**
