### PR TITLE
[testing-devel] lockfiles: drop graduated overrides 🎓

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by remove-graduated-overrides [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/remove-graduated-overrides.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/remove-graduated-overrides.yml)).

### CODE REVIEW

**Review by lucab — DISMISSED** [review]
This is currently causing a downgrade and dropping the punycode security fixes.

**Comment by dustymabe** [comment]
> This is currently causing a downgrade and dropping the punycode security fixes.

maybe mirroring issue where the GH action was seeing one thing and the CI run saw something different? At least we have the check :)

**Review by dustymabe — DISMISSED** [review]

**Comment by dustymabe** [comment]
actually - this won't pass until the next run of `bump-lockfile` it makes sense now.

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
