### PR TITLE
Misc: add a small tool to graph manifest includes

### PR DESCRIPTION
**Pull request by jbtrystram**
This is a simple script that display a tree of manifest includes. I wrote it as a quick tool to get an idea of how manifest were structured.
Requires the `anytree` python lib.
Simply pass the manifest you want to start from as an argument.
Sample output on RHCOS:
```
(L)manifest.yaml
└── (L)manifest-rhel-coreos-9.yaml
    └── manifest-rhel-9.2.yaml
        ├── common.yaml
        │   ├── fedora-coreos-config/manifests/system-configuration.yaml
        │   ├── fedora-coreos-config/manifests/ignition-and-ostree.yaml
        │   │   └── fedora-coreos-config/manifests/bootable-rpm-ostree.yaml
        │   ├── fedora-coreos-config/manifests/file-transfer.yaml
        │   ├── fedora-coreos-config/manifests/networking-tools.yaml
        │   ├── fedora-coreos-config/manifests/user-experience.yaml
        │   ├── fedora-coreos-config/manifests/shared-workarounds.yaml
        │   └── packages-rhcos.yaml
        └── packages-openshift.yaml
```

Agreed I would have spent less time doing it by hand, but it's not every day you get to write some recursive code ! 
I thought I'd share if that can be helpful to someone else. 
It's probably not the best place for it, let me know  !

### CODE REVIEW

**Comment by dustymabe** [comment]
This actually looks pretty cool.

Maybe it would best fit in the COSA repo? or maybe rpm-ostree somewhere. Not sure.

**Comment by mike-nguyen** [comment]
This would have been useful a few weeks ago when I was trying to track down where a package was being added!

I agree with Dusty that maybe rpm-ostree or cosa would be good places so we can use it in RHCOS or FCOS.

**Comment by c4rt0** [comment]
I'm not sure what is the best place for it, but I agree with Dusty, this looks cool.

**Comment by jbtrystram** [comment]
I'll move this to cosa

**Pull request closed without merging**
