### PR TITLE
fedora-coreos-base: add nm-cloud-setup, forward platform variables

### PR DESCRIPTION
**Pull request by lucab**
This adds nm-cloud-setup package to fedora-coreos-base set,
and configures the relevant environment variable for AWS, Azure,
and GCP.

Ref: https://github.com/coreos/fedora-coreos-tracker/issues/320

### CODE REVIEW

**Comment by lucab** [comment]
I tested this manually with a custom image on GCP without further changes, the result looks like this:
```
$ systemctl status nm-cloud-setup.timer
* nm-cloud-setup.timer - Periodically run nm-cloud-setup
     Loaded: loaded (/usr/lib/systemd/system/nm-cloud-setup.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Thu 2020-12-03 11:52:11 UTC; 4min 33s ago
    Trigger: Thu 2020-12-03 11:56:42 UTC; 2s ago
   Triggers: * nm-cloud-setup.service

Dec 03 11:52:11 lbruno-nm-dev2 systemd[1]: Started Periodically run nm-cloud-setup.

$ systemctl status nm-cloud-setup.service 
* nm-cloud-setup.service - Automatically configure NetworkManager in cloud
     Loaded: loaded (/usr/lib/systemd/system/nm-cloud-setup.service; disabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/nm-cloud-setup.service.d
             `-env-gcp.conf
     Active: inactive (dead) since Thu 2020-12-03 11:56:45 UTC; 5s ago
TriggeredBy: * nm-cloud-setup.timer
    Process: 1159 ExecStart=/usr/libexec/nm-cloud-setup (code=exited, status=0/SUCCESS)
   Main PID: 1159 (code=exited, status=0/SUCCESS)

Dec 03 11:56:45 lbruno-nm-dev2 systemd[1]: Starting Automatically configure NetworkManager in cloud...
Dec 03 11:56:45 lbruno-nm-dev2 systemd[1]: nm-cloud-setup.service: Succeeded.
Dec 03 11:56:45 lbruno-nm-dev2 systemd[1]: Finished Automatically configure NetworkManager in cloud.
```

**Comment by dustymabe** [comment]
Any negatives to adding this? Any side effects people wouldn't expect?

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by cgwalters** [comment]
OK wait can someone outline here (or link me to) a summary of what this will do today?  From [this message](https://lists.fedoraproject.org/archives/list/cloud@lists.fedoraproject.org/message/FSQR6KL4KA37WHTUAXL774SXSWIBSYGI/) I see we'll gain support for secondary interfaces on EC2.  Is there anything else it does today?  Does it do anything in GCP or did you just test the service runs successfully?

Aren't there potential concerns about upgrades here?  If as a FCOS user in EC2, I am manually configuring these secondary interfaces via Ignition or something else, will adding nm-cloud-setup break that?

**Comment by jlebon** [comment]
Hmm, yeah it doesn't seem like there's any official documentation for nm-cloud-setup as far as I can tell. I filed https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/600 for upstream.

**Comment by lucab** [comment]
Unfortunately I don't have those details nor intimate knowledge of the codebase.
I only tested that the glue worked on GCP. We are only glueing the timer on newly provisioned nodes, so I don't expect upgrade woes.

Upstream expectation is that
> [...] cloud images could install and enable the tool, so you boot a (Fedora) image and networking would just work.

I guess we can double-check with @thom311 @bengal @ichigo663 any further doubts.

From our side, if we decide to land this new component, the `base.platform.d/` approach indeed works and was originally suggested by @bgilbert and @arithx.

**Comment by travier** [comment]
Docs have been pushed to: https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/nm-cloud-setup.html

**Comment by lucab** [comment]
Rebased, dropped the timer enabling bits, see https://github.com/coreos/fedora-coreos-tracker/issues/320#issuecomment-791492732 for context.

**Comment by LorbusChris** [comment]
:tada:
LGTM
I'd say let's get this in and play with enabling it downstream over in okd-machine-os

**Review by travier — APPROVED** [review]

**Review by jlebon — APPROVED** [review]
Should we add to our presets a `disable nm-cloud-setup.timer` just in case the base Fedora default gets flipped in the future?

**Comment by lucab** [comment]
@jlebon that's very very unlikely. The service needs a platform environment flag to function properly, so the package/distro can't just unconditionally enable the timer (expecting that to work out of the box).

**Pull request merged**
