### PR TITLE
[rawhide] overrides: remove json-glib pin

### PR DESCRIPTION
**Pull request by marmijo**
There is a fix upstream for the issue, but we can just add the broken
symlink to the allowlist for the kola test 'validate-symlinks' and
unpin to pick up the latest f42 package.

see: https://bugzilla.redhat.com/show_bug.cgi?id=2297094

### CODE REVIEW

**Comment by marmijo** [comment]
This will need a rebase and a quick edit after https://github.com/coreos/fedora-coreos-config/pull/3115 merges

**Comment by travier** [comment]
Let's hold for https://github.com/coreos/fedora-coreos-config/pull/3115

**Comment by jlebon** [comment]
Once the config-bot syncs over the test changes from https://github.com/coreos/fedora-coreos-config/pull/3109 to rawhide, we can rebase this to just be about the overrides removal.

**Comment by travier** [comment]
Does the bot really syncs branched commits to rawhide?

**Comment by jlebon** [comment]
> Does the bot really syncs branched commits to rawhide?

https://github.com/coreos/fedora-coreos-config/pull/3109#issuecomment-2315803478

**Comment by travier** [comment]
Will rebase on top of https://github.com/coreos/fedora-coreos-config/pull/3129

**Comment by dustymabe** [comment]
since https://github.com/coreos/fedora-coreos-config/pull/3129 merged and has synced to the `rawhide` branch (via config-bot) now all that is left to do here is drop the pin.

This PR has been updated by @travier to do just that.

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
