### PR TITLE
Draft: Test selinux-policy-41.10-1.fc41

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by jbtrystram** [comment]
Note : This also remove the pins for systemd so  systemd-256  is pulled in

**Comment by zpytela** [comment]
I did not do anything but copied from https://github.com/coreos/fedora-coreos-config/pull/3071

I am mainly interested if there is no direct regression and if at least some problems were fixed

**Comment by jlebon** [comment]
The tests were all timing out so the run was taking much longer than usual, so I added `enforcing=0` in the hope of at least getting some results back faster. But it looks like they're still timing out.

**Comment by aaradhak** [comment]
On testing with this PR changes locally, the kola test `basic` failed .

```
[coreos-assembler]$ kola run basic
⏭️  Skipping kola test pattern "fcos.internet":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
⏭️  Skipping kola test pattern "podman.workflow":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
=== RUN   basic
^[[B^[[B^[[B^[[B2024-07-23T16:51:04Z kola: Test timed out. Adding as candidate for rerun success: basic
--- FAIL: basic (602.79s)
        harness.go:106: TIMEOUT[10m0s]: SSH unsuccessful within allotted timeframe for f0b6c94e-7481-4471-9814-23823df76952.
FAIL, output in tmp/kola/qemu-2024-07-23-1641-17212

```


AVC denials from the console log:

```
Welcome to ^[[0;38;2;60;110;180mFedora CoreOS 41.20240723.dev.0^[[0m!^M
^M^M
[   12.581023] systemd[1]: Initializing machine ID from VM UUID.^M
[   12.778884] systemd[1]: bpf-restrict-fs: LSM BPF program attached^M
[   12.793091] audit: type=1400 audit(1721752882.319:3): avc:  denied  { map } for  pid=1331 comm="coreos-installe" path="/usr/bin/bash" dev="vda4" ino=255880 scontext=system_u:system_r:coreos_installer_generator_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file permissive=1^M
[   12.801108] audit: type=1400 audit(1721752882.325:4): avc:  denied  { execute } for  pid=1331 comm="coreos-installe" path="/usr/bin/bash" dev="vda4" ino=255880 scontext=system_u:system_r:coreos_installer_generator_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file permissive=1^M
[   12.805163] audit: type=1400 audit(1721752882.327:5): avc:  denied  { map } for  pid=1332 comm="coreos-liveiso-" path="/usr/bin/bash" dev="vda4" ino=255880 scontext=system_u:system_r:coreos_liveiso_autologin_generator_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file permissive=1^M
[   12.809173] audit: type=1400 audit(1721752882.327:6): avc:  denied  { execute } for  pid=1332 comm="coreos-liveiso-" path="/usr/bin/bash" dev="vda4" ino=255880 scontext=system_u:system_r:coreos_liveiso_autologin_generator_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file permissive=1^M
[   12.847845] audit: type=1400 audit(1721752882.374:7): avc:  denied  { read } for  pid=1331 comm="coreos-installe" name="passwd" dev="vda4" ino=6913681 scontext=system_u:system_r:coreos_installer_generator_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file permissive=1^M
[   12.855973] audit: type=1400 audit(1721752882.379:8): avc:  denied  { open } for  pid=1331 comm="coreos-installe" path="/etc/passwd" dev="vda4" ino=6913681 scontext=system_u:system_r:coreos_installer_generator_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file permissive=1^M
[   12.860232] audit: type=1400 audit(1721752882.379:9): avc:  denied  { getattr } for  pid=1331 comm="coreos-installe" path="/etc/passwd" dev="vda4" ino=6913681 scontext=system_u:system_r:coreos_installer_generator_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file permissive=1^M
[   12.863940] audit: type=1400 audit(1721752882.380:10): avc:  denied  { read } for  pid=1333 comm="coreos-sulogin-" name="passwd" dev="vda4" ino=6913681 scontext=system_u:system_r:coreos_sulogin_force_generator_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file permissive=1^M
[   12.868133] audit: type=1400 audit(1721752882.380:11): avc:  denied  { open } for  pid=1333 comm="coreos-sulogin-" path="/etc/passwd" dev="vda4" ino=6913681 scontext=system_u:system_r:coreos_sulogin_force_generator_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file permissive=1^M
[   13.032475] zram_generator::config[1365]: No configuration found.^M
[   13.071398] Guest personality initialized and is inactive^M
[   13.073107] VMCI host device registered (name=vmci, major=10, minor=123)^M
[   13.074272] Initialized host personality^M
[   13.087557] NET: Registered PF_VSOCK protocol family^M
[   13.602017] systemd[1]: Populated /etc with preset unit settings.^M
[   14.036767] systemd[1]: run-credentials-systemd\x2djournald.service.mount: Deactivated successfully.^M
[   14.039498] systemd[1]: initrd-switch-root.service: Deactivated successfully.^M
[   14.041176] systemd[1]: Stopped initrd-switch-root.service - Switch Root.^M
/avc                                                                                 
```

**Comment by zpytela** [comment]
Seems to match my results which effected in this pr https://github.com/fedora-selinux/selinux-policy/pull/2255

Never mind if you cannot use the pr's copr build, I'll create a new rawhide build soon.

**Pull request closed without merging**
