### PR TITLE
overlay: disable dracut stripping

### PR DESCRIPTION
**Pull request by jlebon**
While looking at the boot space issue[1], I tested whether stripping
binaries saved anything. Currently, dracut tries to strip binaries if
`strip` (or `eu-strip`) are available, which isn't the case in FCOS.

Adding it as a test, it turns out stripping barely saves anything
because we've already split out debug symbols into separate RPMs, and
the remaining symbols don't take much space.

So let's just tell dracut to stop trying to opportunistically strip
anything to be consistent. This then squashes a message emitted about
`strip` not being found.

[1] https://github.com/coreos/fedora-coreos-tracker/issues/1247

### CODE REVIEW

**Comment by dustymabe** [comment]
do we want to share this with rhcos.. maybe we rename to file to something more generic? `coreos_nostrip`?

**Review by dustymabe — APPROVED** [review]

**Comment by jlebon** [comment]
The file will be shared with RHCOS. The naming I used follows the current naming convention for the other dropins, though I agree we should probably rename them `s/fcos/coreos/`.

**Comment by dustymabe** [comment]
> though I agree we should probably rename them `s/fcos/coreos/`.

any chance you want to do that in this pass?

**Comment by jlebon** [comment]
> > though I agree we should probably rename them `s/fcos/coreos/`.
> 
> any chance you want to do that in this pass?

Will do it separately to avoid wasting good CI. That also gives a better place for Colin to chime in in case there's a reason we used `fcos_` there.

**Comment by jlebon** [comment]
> Will do it separately to avoid wasting good CI.

https://github.com/coreos/fedora-coreos-config/pull/1858

**Pull request merged**
