### PR TITLE
[testing] tree: promote changes from testing-devel at 262ea8b2b031a81a3cb379a93803ebdc2d407709

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @dustymabe in https://github.com/coreos/fedora-coreos-streams/issues/994.

### CODE REVIEW

**Review by c4rt0 — DISMISSED** [review]
/lgtm

**Review by dustymabe — DISMISSED** [review]
LGTM

**Review by marmijo — DISMISSED** [review]
LGTM

**Comment by marmijo** [comment]
Looks like CI is failing because of the bootc submodule. This happened during the last releases as well: https://github.com/coreos/fedora-coreos-config/pull/3279#issuecomment-2496451031

**Comment by dustymabe** [comment]
I just hit the easy button for now and pushed a commit to drop the submodule again.

**Comment by dustymabe** [comment]
CI still isn't working. I'm merging this and will deal with any consequences later.

**Pull request merged**
