### PR TITLE
tests/reboot: reboot 10 times

### PR DESCRIPTION
**Pull request by dustymabe**
This just confirms there aren't somehow issues with rebooting multiple
times.

### CODE REVIEW

**Comment by dustymabe** [comment]
I'm not convinced we should do this but I had made changes to the code last week and am interested in what others think.

**Comment by jlebon** [comment]
Is this motivated by some recent regression?

**Comment by dustymabe** [comment]
> Is this motivated by some recent regression?

when investigating https://github.com/coreos/fedora-coreos-tracker/issues/1756 i was initially suspicious (since the failure always seemed to occur with secureboot enabled) that there was some fragility in rebooting uefi-secure machines many times so I modified this test to help me prove or disprove that theory.

**Comment by jbtrystram** [comment]
It feels a bit weird to test more than once IMO. Do we trust our stuff to be indempotent ?

**Comment by dustymabe** [comment]
I'll close this out. I mostly posted it up because I had written the code and wanted to see if anyone else thought it was a good idea. The code will be here in case we ever want it in the future.

**Pull request closed without merging**
