### PR TITLE
overrides: pin rust-afterburn-5.4.0-2.fc38

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @marmijo via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Review by bgilbert — APPROVED** [review]

**Review by jlebon — APPROVED** [review]
I think we need a similar one for rawhide too?

**Comment by marmijo** [comment]
yes, see: https://github.com/coreos/fedora-coreos-config/pull/2415

**Comment by marmijo** [comment]
CI failed with 
`[2023-05-10T17:53:39.427Z] Downgrade detected. This is likely unintentional. If not, you may safely ignore this error.`
This is probably expected. How do we ignore it?

**Comment by jlebon** [comment]
You can merge it in manually after verifying that the diff is indeed what we expected. (It is, but I'll let you do the honours. :) )

**Comment by bgilbert** [comment]
That only works for repo administrators, though.  Ideally we'd break out the downgrade test into a separate non-required CI run to avoid that issue.

**Comment by bgilbert** [comment]
Filed as https://github.com/coreos/fedora-coreos-config/issues/2416.

**Pull request merged**
