### PR TITLE
[testing] tree: promote changes from next at d96411f3f604b05b79efcc072e5d4486530a95fe

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @c4rt0 in https://github.com/coreos/fedora-coreos-streams/issues/883.

### CODE REVIEW

**Review by c4rt0 — DISMISSED** [review]
/lgtm

**Review by aaradhak — DISMISSED** [review]

**Comment by jlebon** [comment]
Wait, no. This is missing the commit to rebase to Fedora 40.

**Comment by jlebon** [comment]
Ahhh OK, I see Dusty had done the right thing but then we retriggered the promotion GHA by re-adding the `ok-to-promote` label.

I've updated this now to promote again from the last next release. Do not remove and re-add the `ok-to-promote` label! :)

"Check promotion diffs" workflow failure is expected.

The true diff is:

```diff
$ git diff d96411f3f604b05b79efcc072e5d4486530a95fe
diff --git a/manifest.yaml b/manifest.yaml
index cced1895..4a558db0 100644
--- a/manifest.yaml
+++ b/manifest.yaml
@@ -1,5 +1,5 @@
 variables:
-  stream: next
+  stream: testing
   prod: true

 releasever: 40
```

**Comment by c4rt0** [comment]
You got me scared there for a second :) 

edit: Thanks for keeping an eye on this!

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Pull request merged**
