### PR TITLE
overlay.d: delete `cosa-no-autolayer` knob file

### PR DESCRIPTION
**Pull request by jlebon**
It's the default behaviour now:
https://github.com/coreos/coreos-assembler/pull/2665

### CODE REVIEW

**Comment by jlebon** [comment]
This is the final step in https://github.com/coreos/coreos-assembler/pull/2641#issuecomment-1013285699.

**Comment by jlebon** [comment]
Let's wait a day or two on this to be nice because it's another cosa bump required on local developer machines and the stamp file doesn't really hurt there until then.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
ready for merge soon?

**Comment by jlebon** [comment]
> ready for merge soon?

We need to revert https://github.com/coreos/coreos-assembler/pull/2667 first which is gated on https://github.com/coreos/fedora-coreos-streams/issues/454. (Edit: added a checkbox there so we don't forget.)

**Comment by dustymabe** [comment]
Got ya. Thanks.

**Comment by jlebon** [comment]
Now just needs https://github.com/coreos/coreos-assembler/pull/2711.

**Comment by jlebon** [comment]
Now that we have new cosa, we can finally merge this!

**Pull request merged**
