### PR TITLE
manifests/fedora-coreos-base: explicitly add `xen-blkfront` to initrd

### PR DESCRIPTION
**Pull request by bgilbert**
Dracut currently fails to do this for 5.14 kernels, breaking boot on Xen-based EC2 instances.

Addresses https://github.com/coreos/fedora-coreos-tracker/issues/997.

### CODE REVIEW

**Comment by bgilbert** [comment]
Tested on `t2.micro` and `m4.large`.  Ready for review.

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by miabbott — APPROVED** [review]
LGTM; kudos for the test

**Review by jlebon — APPROVED** [review]
Thanks for digging into this!

**Comment by dustymabe** [comment]
The fix has already been deployed to `rawhide` 🎉

But this means the test is now failing for rawhide. I'll open a PR to denylist the test on `rawhide`, `next`, `next-devel`. Once it hits `testing-devel` we can remove the workaround (and the test).

**Comment by bgilbert** [comment]
Bodhi updates: [F34](https://bodhi.fedoraproject.org/updates/FEDORA-2021-e4843341ca), [F35](https://bodhi.fedoraproject.org/updates/FEDORA-2021-5918c936f8)

**Pull request merged**
