### PR TITLE
[stable] tree: promote changes from testing at 07b1de960009ca66245f71a498c380e53581346b

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @marmijo in https://github.com/coreos/fedora-coreos-streams/issues/747.

### CODE REVIEW

**Comment by dustymabe** [comment]
CI failed with:

```
FAIL: iso-offline-install-fromram.4k.uefi
```

Can we add a 2nd commit to this PR that denylists that test? That new feature is only in latest `testing-devel` so it won't pass this round.

**Comment by marmijo** [comment]
> Can we add a 2nd commit to this PR that denylists that test? 

Sure, I'll add that now

**Comment by dustymabe** [comment]
actually there are a few more - all added in https://github.com/coreos/coreos-assembler/commit/0955101533acae9b72f155136f5c7a9d1fdbbc00 

```
iso-offline-install-fromram.4k.uefi
iso-offline-install-fromram.ppcfw
iso-offline-install-fromram.uefi
```

**Comment by marmijo** [comment]
I added the three tests to the denylist in a seperate commit. `Check promotion diffs` is now failing because the changes were unexpected. We should be good to ignore this.

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
