### PR TITLE
[rhcos-4.10] Bug 6692: Lazily unmount /proc/cmdline

### PR DESCRIPTION
**Pull request by c4rt0**
See: https://issues.redhat.com/browse/OCPBUGS-6692

It's possible that some other process has a file descriptor open for `/proc/cmdline`; if so our unmount will fail.  Do the unmount lazily - it was designed for exactly this situation.

This was seen in an OCP installation on vSphere at least once.

### CODE REVIEW

**Comment by dustymabe** [comment]
I think we need to do a few things here:

- if this is needed in `4.10` then we should backport it to `4.12` and `4.11` first.
- we should do a legit cherry pick commit (where the commit message says `cherry picked from xyz`.

**Comment by travier** [comment]
You can use `cherrypick -x` to get something with a standard format

**Comment by travier** [comment]
Or use Prow's `/cherrypick` command

**Comment by c4rt0** [comment]
Let me start by saying that I can see what I have done with the last `git push --force`. I'm working on it...
Thanks for the comments!

**Comment by c4rt0** [comment]
> Or use Prow's `/cherrypick` command

Can't find any docs related to the Prow's `/cherrypick` command

**Comment by travier** [comment]
See https://prow.k8s.io/command-help

**Review by travier — DISMISSED** [review]

**Comment by travier** [comment]
Nit: Needs a space in the commit title after the branch name

**Comment by c4rt0** [comment]
@travier - nit-pick corrected. Thanks!

**Review by travier — DISMISSED** [review]

**Comment by c4rt0** [comment]
@travier Since it's an older branch and the [CI isn't going to pass here,](https://github.com/coreos/fedora-coreos-config/pull/2108#issuecomment-1329757512) can we just merge it and ignore the bot?

**Comment by jlebon** [comment]
Recently, we've disabled CI by [just replacing the contents of `.cci.jenkinsfile`](https://github.com/coreos/fedora-coreos-config/commit/746437de69e508330a07007b06aba218561b9a76) in these RHCOS branches. We haven't done it yet for `rhcos-4.10`. Want to cherry-pick that commit too while you're here?

**Comment by c4rt0** [comment]
@jlebon Absolutely, thanks!

**Review by jlebon — APPROVED** [review]

**Pull request merged**
