### PR TITLE
[next-devel] overrides: fast-track downgraded packages

### PR DESCRIPTION
**Pull request by aaradhak**
F40 is in final freeze. We are fast-tracking the downgraded packages.

```
Downgraded:
  amd-gpu-firmware 20240410-1.fc39 -> 20240312-1.fc40
  amd-ucode-firmware 20240410-1.fc39 -> 20240312-1.fc40
  atheros-firmware 20240410-1.fc39 -> 20240312-1.fc40
  brcmfmac-firmware 20240410-1.fc39 -> 20240312-1.fc40
  intel-gpu-firmware 20240410-1.fc39 -> 20240312-1.fc40
  libbsd 0.12.2-1.fc39 -> 0.11.7-7.fc40
  libnfsidmap 1:2.6.4-0.rc6.fc39 -> 1:2.6.4-0.rc5.fc40
  libxmlb 0.3.18-1.fc39 -> 0.3.17-1.fc40
  linux-firmware 20240410-1.fc39 -> 20240312-1.fc40
  linux-firmware-whence 20240410-1.fc39 -> 20240312-1.fc40
  mt7xxx-firmware 20240410-1.fc39 -> 20240312-1.fc40
  nfs-utils-coreos 1:2.6.4-0.rc6.fc39 -> 1:2.6.4-0.rc5.fc40
  nvidia-gpu-firmware 20240410-1.fc39 -> 20240312-1.fc40
  nxpwireless-firmware 20240410-1.fc39 -> 20240312-1.fc40
  realtek-firmware 20240410-1.fc39 -> 20240312-1.fc40
  rpm-ostree 2024.4-6.fc39 -> 2024.4-5.fc40
  rpm-ostree-libs 2024.4-6.fc39 -> 2024.4-5.fc40
  tiwilink-firmware 20240410-1.fc39 -> 20240312-1.fc40
  vim-data 2:9.1.264-1.fc39 -> 2:9.1.181-1.fc40
  vim-minimal 2:9.1.264-1.fc39 -> 2:9.1.181-1.fc40
```

_Note:_ 
Fast-tracking `podman-5.0.1-1.fc40` as the Fedora test day reports show that some issues were fixed with the new version.
F40 Test day: https://testdays.fedoraproject.org/events/179

_Ref:_ https://github.com/coreos/fedora-coreos-tracker/issues/1674#issuecomment-2010200582

### CODE REVIEW

**Comment by dustymabe** [comment]
only use `evra` if you are going to add an architecture to the entry.. i.e. `.x86_64` or `.noarch`

**Comment by aaradhak** [comment]
> only use `evra` if you are going to add an architecture to the entry.. i.e. `.x86_64` or `.noarch`

yea, I missed adding the `.noarch` in the linux-firmware packages. I have updated them now.

**Comment by gursewak1997** [comment]
The Podman change [commit's](https://github.com/coreos/fedora-coreos-config/pull/2967/commits/6e206090896f1ee0ad64362d2f9ffce1dca90932) got the `.noarch` changes in addition to Podman package addition. Might be ideal to add those changes to the first commit. 
LGTM otherwise

**Comment by aaradhak** [comment]
> The Podman change [commit's](https://github.com/coreos/fedora-coreos-config/pull/2967/commits/6e206090896f1ee0ad64362d2f9ffce1dca90932) got the `.noarch` changes in addition to Podman package addition. Might be ideal to add those changes to the first commit. LGTM otherwise

Fixed it.

**Review by gursewak1997 — APPROVED** [review]

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by marmijo — APPROVED** [review]

**Pull request merged**
