### PR TITLE
overrides: fasttrack rust-zincati-0.0.9-1.fc31

### PR DESCRIPTION
**Pull request by dustymabe**
New version that includes various fixes and also support
for running behind a proxy.

### CODE REVIEW

**Comment by dustymabe** [comment]
will update the link to bodhi once the update is made

**Comment by dustymabe** [comment]
> will update the link to bodhi once the update is made

done - ready for review

**Review by jlebon — APPROVED** [review]

**Comment by jlebon** [comment]
Upgrade testing should at least sanity-check basic functionality in the new Zincati. (But since the zincati repo itself has that test in its CI, we shouldn't expect any surprises here. :) )

**Comment by dustymabe** [comment]
will merge once CI passes

**Pull request merged**
