### PR TITLE
[rawhide] overrides: Remove pin for glib2-2.74.1-3.fc38 in rawhide

### PR DESCRIPTION
**Pull request by gursewak1997**
Related Issue: https://github.com/coreos/fedora-coreos-tracker/issues/1422

### CODE REVIEW

**Comment by dustymabe** [comment]
@travier - it appears the toolbox test still isn't passing (even though the container does exist now) - can you take a look?

**Comment by travier** [comment]
Highly likely that polkit has been rebuild / linked against the new glib which we reverted.

**Comment by travier** [comment]
```
kola-runext-podman-tmpfs-context[2025]: /usr/bin/conmon: symbol lookup error: /usr/bin/conmon: undefined symbol: g_string_free_and_steal
```

**Comment by travier** [comment]
Everything rebuilt against the new glib will start failing

**Comment by travier** [comment]
I'm pushing the new rpm-ostree build so that we can update glib again

**Comment by travier** [comment]
Hold on, this is rawhide, we should be able to unpin glib now that rpm-ostree is fixed there.

**Comment by travier** [comment]
So this should unpin glib instead

**Review by aaradhak — APPROVED** [review]

**Pull request merged**
