### PR TITLE
[rhcos-4.7] Backport patches for lsblk workaround and prjquota

### PR DESCRIPTION
**Pull request by jlebon**
I.e. #900 (for https://bugzilla.redhat.com/show_bug.cgi?id=1934863) and #903 (for https://bugzilla.redhat.com/show_bug.cgi?id=1940966).

### CODE REVIEW

**Review by miabbott — APPROVED** [review]
Will wait for CI to successfully finish before merging

**Comment by jlebon** [comment]
CI here likely will fail unfortunately because it's building with latest cosa instead of the 4.7 branch.

**Review by cgwalters — APPROVED** [review]
Maybe what we really want to do is fork this repo into openshift/ and have the branches there, and use Prow CI jobs that will naturally follow forking, etc.

**Comment by miabbott** [comment]
> CI here likely will fail unfortunately because it's building with latest cosa instead of the 4.7 branch.

Will do a local test with `cosa:rhcos-4.7` to be certain

**Comment by miabbott** [comment]
> PASS, output in tmp/kola

Looks good locally. Ran `kola run` and `kola --basic-qemu-scenarios`

/lgtm

**Comment by miabbott** [comment]
> /override continuous-integration/jenkins/pr-merge

Oops, forgot that we don't use Prow for merging here

**Pull request merged**
