### PR TITLE
tests/kola: New `basic` test using kola external tests

### PR DESCRIPTION
**Pull request by cgwalters**
Pairs with https://github.com/coreos/coreos-assembler/pull/1252

The motivation here is to get the ball rolling for (where it
makes sense) to have a place to add tests corresponding to changes
in this repository.

### CODE REVIEW

**Comment by jlebon** [comment]
I think we can rebase this and hook it to CI now, right?

**Comment by cgwalters** [comment]
https://github.com/coreos/coreos-ci-lib/pull/16 is needed for that I think?

**Comment by cgwalters** [comment]
> kola -p qemu-unpriv --cosa-build builds/31.20200323.dev.0/x86_64/meta.json --output-dir tmp/kola run --parallel 8 --exttest /home/jenkins/agent/workspace/fedora-coreos-config_PR-305-SSTLEFOEQFEC2YX4HET64ZVVRA6NFO2WH635C5TPPTS24FJGCQPQ -E src/config
>
> panic: test ext.fedora-coreos-config_PR-305-SSTLEFOEQFEC2YX4HET64ZVVRA6NFO2WH635C5TPPTS24FJGCQPQ already registered

Oh heh of course the "automatic src/config" registration fails when the repo under CI *is* the config repo.

**Comment by cgwalters** [comment]
https://github.com/coreos/coreos-ci-lib/pull/18

**Comment by cgwalters** [comment]
> --- PASS: ext.fedora-coreos-config_PR-305-SSTLEFOEQFEC2YX4HET64ZVVRA6NFO2WH635C5TPPTS24FJGCQPQ (28.48s)


:tada:

**Comment by cgwalters** [comment]
OK, restarted that test and back to green!

**Review by jlebon — APPROVED** [review]
LGTM!

**Comment by jlebon** [comment]
Re.

> > --- PASS: ext.fedora-coreos-config_PR-305-SSTLEFOEQFEC2YX4HET64ZVVRA6NFO2WH635C5TPPTS24FJGCQPQ (28.48s)
> 
> :tada:

Shouldn't this be broken down by test here? So e.g. `ext.fedora-coreos-config....basic` ?

**Comment by cgwalters** [comment]
> Shouldn't this be broken down by test here? So e.g. ext.fedora-coreos-config....basic ?

That will happen automatically when there are multiple executables in the directory.

**Pull request merged**
