### PR TITLE
[testing] tree: promote changes from testing-devel at 2a2a9de 

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Review by travier — COMMENTED** [review]
I might have missed something but it looks like this is now keeping systemd-networkd (not removing it). Maybe we also need to cherry-pick https://github.com/coreos/fedora-coreos-config/commit/f7c0d22426355b1e1d51cd760f2409a54df90423 to this branch?

**Comment by lucab** [comment]
@travier good catch. There is something fishy going on here as that commit is already part of the branch being promoted but... only half of that commit is part of this PR. I'm confused...

**Comment by lucab** [comment]
Ah nevermind, that is the result of the explicit exclusion command at https://github.com/coreos/fedora-coreos-releng-automation/blob/master/scripts/promote-config.sh#L32-L33.
I've added an additional commit on top to bring the removal rules back.

**Comment by dustymabe** [comment]
CI has been down and we haven't been able to merge https://github.com/coreos/fedora-coreos-config/pull/654

Let's merge that first?

**Comment by lucab** [comment]
@dustymabe yes, it will make the history cleaner and anyway CI didn't run yet on this one.

**Comment by dustymabe** [comment]
Since #654 has merged (and passed CI) we can rebase this now.

**Comment by lucab** [comment]
Rebased. I've dropped the manual manifest tweak too, it effectively became an empty commit.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
had to bump the koji tagger. some of the rpms were missing in `coreos-pool`.

**Review by jlebon — APPROVED** [review]

**Comment by dustymabe** [comment]
```
--- FAIL: ext.fedora-coreos-config_PR-663-7AAYQKQL5ESJ5LBYJGGT7LNREKYUV6B7JUEXITI5BYD2ABEGH2WQ.root-reprovision.luks (5028.86s)
        harness.go:926: Cluster failed starting machines: machine "2115750f-0961-40db-a89a-a5c3b064fb05" failed to start: ssh journalctl failed: ssh: handshake failed: read tcp 127.0.0.1:54976->127.0.0.1:46299: read: connection reset by peer

```

**Comment by dustymabe** [comment]
a later CI run worked \o/

**Pull request merged**
