### PR TITLE
[next-devel] overrides: fast-track dracut-059-2.fc38

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @dustymabe via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Comment by dustymabe** [comment]
Will rebase this once the bump-lockfile run finishes (should make CI pass).

**Comment by jlebon** [comment]
Hmm, this is fast-tracking it right before re-releasing f38. I'd personally prefer we skip it for this release and land it right after the promotion.

**Comment by dustymabe** [comment]
The only reason I think it'd be nice to get it in here is because this is probably what we'll be executing tests for test day on.

I'm cool with leaving it until next time too.

Either way this PR should be able to be merged, we'll just wait until after promotion if we don't want it to go into the release we're going to build today.

**Comment by jlebon** [comment]
> I'm cool with leaving it until next time too.

:+1: I'm not strongly opposed either. Just that this dracut release looks like it has a lot of changes, and given our many integration points with it, I'd prefer to have it bake more. The Bodhi update is still fresh and hasn't really seen any testing yet it looks like.

> Either way this PR should be able to be merged, we'll just wait until after promotion if we don't want it to go into the release we're going to build today.

Yeah, that's what I mean but it likely wasn't clear enough. :) It'll also allow us to provide negative feedback on the Bodhi update if needed.

**Comment by dustymabe** [comment]
rebased

**Review by jlebon — APPROVED** [review]

**Pull request merged**
