### PR TITLE
tests: fix skip no-persist-ip on s390x

### PR DESCRIPTION
**Pull request by HuijingHei**

### CODE REVIEW

**Comment by travier** [comment]
Aparrently '!' has a meaning in YAML so we need quotes: https://stackoverflow.com/questions/9664113/what-does-a-single-exclamation-mark-do-in-yaml

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Can you check all other tests?

**Comment by travier** [comment]
If you could convert all other tests to the new YAML format that would be great too

**Review by jlebon — APPROVED** [review]
Thanks!

**Comment by jlebon** [comment]
This should fix existing known test failures, so let's get this in and do any other cleanups as follow-ups.

**Comment by jlebon** [comment]
> If you could convert all other tests to the new YAML format that would be great too

```
$ git grep 'kola: {' tests/kola | wc -l
89
```

Hmm, that's more work than the comment implies. Let's track that in a GitHub issue and see if someone wants to tackle it?

**Comment by travier** [comment]
> Hmm, that's more work than the comment implies. Let's track that in a GitHub issue and see if someone wants to tackle it?

Agree. Sorry, I was unclear. I was suggesting that a follow-up. I'll make an issue.

**Comment by travier** [comment]
Made https://github.com/coreos/fedora-coreos-config/issues/2106

**Pull request merged**
