### PR TITLE
tree: promote changes from testing-devel at 24d75034c5082fc292e52bdde…

### PR DESCRIPTION
**Pull request by lucab**
…a54997481f65fba

### CODE REVIEW

**Comment by lucab** [comment]
Jenkins is failing with the following output:
```
error: Packages not found: bind-utils, btrfs-progs, fuse-overlayfs, kernel-core, passwd, skopeo, zincati
```

**Comment by jlebon** [comment]
So taking `bind-utils` as an example here. The package is definitely in the pool:

https://koji.fedoraproject.org/koji/buildinfo?buildID=1418980

But not in the yum repo. The tagger itself did wait for it before starting the `distRepo` though:

```
...
2019-12-10 19:48:55,581 INFO coreos_koji_tagger - Waiting on builds to be signed
2019-12-10 19:48:55,581 INFO coreos_koji_tagger - Remaining builds: ['bind-9.11.13-3.fc31', 'passwd-0.80-7.fc31']
Watching tasks (this may be safely interrupted)...
39478636 distRepo (coreos-pool): free
39478636 distRepo (coreos-pool): free -> open (buildvm-20.phx2.fedoraproject.org)
...
```

Ahh yes, I think this is from issues we had yesterday with tag2distrepo not being fully disabled and so it raced with the tagger itself running distRepo. Anyway, I've started a new distRepo now: https://koji.fedoraproject.org/koji/taskinfo?taskID=39484318

**Review by jlebon — APPROVED** [review]
Restarted CI on this.

LGTM otherwise!

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
