### PR TITLE
overlay.d/05core: Fix boot-efi.mount unit dependency

### LINKED ISSUE #115: "enable boot-efi.mount" make ppc64le platform fail
cosa run failed on ppc64le platform.
ppc64le qcow2 generated image does not end its boot and get stuck with no access to login.

The problem is due to the "enable boot-efi.mount" added in 
overlay/usr/lib/systemd/system-preset/42-coreos.preset  for all platforms.
see commit cb3f240
and also #105 and #106 pull requests

I didn't find a fair way to avoid it, please @ajeddeloh could you have a look ?

### PR DESCRIPTION
**Pull request by jcajka**
Fix #115

### CODE REVIEW

**Comment by jcajka** [comment]
For the record tested only on ppc64le, working on other arches atm.

**Review by ajeddeloh — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
@jcajka - can you report back once you've tested on other arches?

**Comment by jcajka** [comment]
> @jcajka - can you report back once you've tested on other arches?

Sure.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/issues/115#issuecomment-520616849

**Comment by bgilbert** [comment]
Won't this still try to pull in the device node, but just make the failure non-fatal?  Conditionalized units still pull in their dependencies even if the condition fails.  Avoiding that generally requires a systemd generator.  https://github.com/coreos/fedora-coreos-config/pull/155 moves `boot-efi.mount` to a generator and enables it only on architectures that support UEFI.

**Comment by cgwalters** [comment]
Yeah, this will be obsoleted by https://github.com/coreos/fedora-coreos-config/pull/155

**Pull request closed without merging**
