### PR TITLE
[next] tree: promote changes from next-devel at 669a3da63a0de95ff6106d666e96dd9c4aeb3f24 

### PR DESCRIPTION
**Pull request by ravanelli**

### CODE REVIEW

**Comment by jlebon** [comment]
(I'm trying to get https://github.com/coreos/fedora-coreos-config/blob/a17210e383ecbe9bd95e656c8e018e9d51ba64da/.github/workflows/promotion-diff.yml#L14 to trigger.)

**Review by jlebon — APPROVED** [review]
I'm not sure why the GitHub Action isn't working properly. But I verified this locally:

```diff
$ git diff upstream/next-devel
diff --git a/manifest.yaml b/manifest.yaml
index 2ffeaf5e..707cdc79 100644
--- a/manifest.yaml
+++ b/manifest.yaml
@@ -1,15 +1,7 @@
 variables:
-  stream: next-devel
-  prod: false
+  stream: next
+  prod: true

 releasever: 36

-repos:
-  # These repos are there to make it easier to add new packages to the OS and to
-  # use `cosa fetch --update-lockfile`; but note that all package versions are
-  # still pinned. These repos are also used by the remove-graduated-overrides
-  # GitHub Action.
-  - fedora-next
-  - fedora-next-updates
-
 include: manifests/fedora-coreos.yaml
```

**Comment by dustymabe** [comment]
CI job passed https://jenkins-coreos-ci.apps.ocp.fedoraproject.org/job/fedora-coreos-config/job/PR-1635/1/display/redirect

**Comment by bgilbert** [comment]
Loosened the title matching in https://github.com/coreos/fedora-coreos-config/pull/1638.

**Pull request merged**
