### PR TITLE
Move to Fedora Linux 40

### PR DESCRIPTION
**Pull request by aaradhak**
The Fedora 40 GA is to be released on Tuesday April 23rd.

Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1674

### CODE REVIEW

**Comment by dustymabe** [comment]
let's maybe go on and change all the other container references too:

```
$ grep -Pri 'registry.fedoraproject.org|quay.io/fedora/fedora:'
ci/buildroot/Dockerfile:FROM quay.io/fedora/fedora:39
tests/kola/selinux/podman-tmpfs-context:context=$(podman run --rm --privileged quay.io/fedora/fedora:39 \
tests/kola/binfmt/qemu:        containerArch=$(podman run --arch=amd64 --rm quay.io/fedora/fedora:39 arch)
tests/kola/podman/dns/test.sh:podman run --rm -t --network=testnetwork quay.io/fedora/fedora:39 getent hosts google.com
tests/kola/podman/rootless-pasta-networking:podman run -i --net=pasta:--mtu,1500 quay.io/fedora/fedora:39 bash <<"EOF"
tests/kola/podman/rootless-systemd:FROM quay.io/fedora/fedora:39
tests/kola/ntp/data/ntplib.sh:FROM quay.io/fedora/fedora:39
tests/kola/docker/basic:docker run --rm quay.io/fedora/fedora:39 true
.github/workflows/add-override.yml:    container: quay.io/fedora/fedora:latest
```

**Comment by aaradhak** [comment]
> grep -Pri 'registry.fedoraproject.org|quay.io/fedora/fedora:'

I have updated it. 

@dustymabe  Is this update usually done ? I didn't see this in the checklist. 

> let's maybe go on and change all the other container references too:
> 
> ```
> $ grep -Pri 'registry.fedoraproject.org|quay.io/fedora/fedora:'
> ci/buildroot/Dockerfile:FROM quay.io/fedora/fedora:39
> tests/kola/selinux/podman-tmpfs-context:context=$(podman run --rm --privileged quay.io/fedora/fedora:39 \
> tests/kola/binfmt/qemu:        containerArch=$(podman run --arch=amd64 --rm quay.io/fedora/fedora:39 arch)
> tests/kola/podman/dns/test.sh:podman run --rm -t --network=testnetwork quay.io/fedora/fedora:39 getent hosts google.com
> tests/kola/podman/rootless-pasta-networking:podman run -i --net=pasta:--mtu,1500 quay.io/fedora/fedora:39 bash <<"EOF"
> tests/kola/podman/rootless-systemd:FROM quay.io/fedora/fedora:39
> tests/kola/ntp/data/ntplib.sh:FROM quay.io/fedora/fedora:39
> tests/kola/docker/basic:docker run --rm quay.io/fedora/fedora:39 true
> .github/workflows/add-override.yml:    container: quay.io/fedora/fedora:latest
> ```

**Comment by dustymabe** [comment]
LGTM

> @dustymabe Is this update usually done ? I didn't see this in the checklist.

we should add it to our checklist probably

**Comment by dustymabe** [comment]
Looks like the `ext.config.selinux.podman-tmpfs-context` test is failing. Mind looking into that?

**Comment by aaradhak** [comment]
> Looks like the `ext.config.selinux.podman-tmpfs-context` test is failing. Mind looking into that?

In the CI logs, it seems that the container exited shortly after starting. The `mount` command was not successfully executed. 

cmd:
```
podman run --rm --privileged quay.io/fedora/fedora:40 \
            bash -c "mount -t tmpfs tmpfs /mnt/ && stat --format '%C' /mnt/
```


Logs:
```
[2024-04-23T20:01:22.206Z] Apr 23 20:01:20 qemu0 gifted_knuth[2318]: bash: line 1: mount: command not found

[2024-04-23T20:01:22.206Z] Apr 23 20:01:20 qemu0 kola-runext-podman-tmpfs-context[2153]: bash: line 1: mount: command not found

[2024-04-23T20:01:22.206Z] Apr 23 20:01:20 qemu0 conmon[2318]: conmon 1624896b2002d6a3a121 <nwarn>: Failed to open cgroups file: /sys/fs/cgroup/machine.slice/libpod-1624896b2002d6a3a121cbfc5b49e3d709e072d2d27a7a615d5a7e5da71d82f1.scope/container/memory.events

[2024-04-23T20:01:22.206Z] Apr 23 20:01:20 qemu0 podman[2153]: 2024-04-23 20:01:20.519959461 +0000 UTC m=+8.330582046 container died 1624896b2002d6a3a121cbfc5b49e3d709e072d2d27a7a615d5a7e5da71d82f1 (image=quay.io/fedora/fedora:40, name=gifted_knuth, org.opencontainers.image.name=fedora, license=MIT, io.buildah.version=1.35.1, vendor=Fedora Project, version=40, org.opencontainers.image.vendor=Fedora Project, org.opencontainers.image.version=40, name=fedora, org.opencontainers.image.license=MIT, org.opencontainers.image.url=https://fedoraproject.org/)

[2024-04-23T20:01:22.206Z] Apr 23 20:01:20 qemu0 podman[2323]: 2024-04-23 20:01:20.673485853 +0000 UTC m=+0.141330054 container remove 1624896b2002d6a3a121cbfc5b49e3d709e072d2d27a7a615d5a7e5da71d82f1 (image=quay.io/fedora/fedora:40, name=gifted_knuth, name=fedora, version=40, io.buildah.version=1.35.1, org.opencontainers.image.name=fedora, org.opencontainers.image.vendor=Fedora Project, org.opencontainers.image.license=MIT, vendor=Fedora Project, org.opencontainers.image.url=https://fedoraproject.org/, org.opencontainers.image.version=40, license=MIT)

```

**Comment by dustymabe** [comment]
looks like F40 got rid of `util-linux-core` package which provides the `mount` command among other things. 

```
[dustymabe@media ~]$ podman run --rm -it quay.io/fedora/fedora:40
Trying to pull quay.io/fedora/fedora:40...
Getting image source signatures
Copying blob 454eac4198a0 done   | 
Copying config 868a0de675 done   | 
Writing manifest to image destination
[root@ed6283400afd /]# which mount
bash: which: command not found
[root@ed6283400afd /]# ls -l /usr/bin/mount
ls: cannot access '/usr/bin/mount': No such file or directory
[root@ed6283400afd /]# rpm -qf /usr/bin/mount
error: file /usr/bin/mount: No such file or directory
[root@ed6283400afd /]# rpm -qa | grep util-linux
```

**Comment by dustymabe** [comment]
xref: https://pagure.io/fedora-kiwi-descriptions/pull-request/45#

**Comment by dustymabe** [comment]
just switch the test over to use `quay.io/fedora/fedora-toolbox:40` to get us unblocked - it sucks because that container is much larger, but oh well.

**Comment by aaradhak** [comment]
> just switch the test over to use `quay.io/fedora/fedora-toolbox:40` to get us unblocked - it sucks because that container is much larger, but oh well.

ok, I will make the change in `podman-tmpfs-context` and push it.

**Comment by dustymabe** [comment]
let's try to improve the commit message of that new commit. Maybe something like:

```
tests/kola: use toolbox container image for selinux.podman-tmpfs-context test

In F40 the base container no longer includes `util-linux-core` so we
can't run the `mount` command. Let's just pull the toolbox container for
now, which does include it.
```

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
