### PR TITLE
[stable] tree: promote changes from testing at 6f0ccf58c0d5f5e6c38d00d9256b300f97e10b7f

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @prestist in https://github.com/coreos/fedora-coreos-streams/issues/699.

### CODE REVIEW

**Review by prestist — DISMISSED** [review]

**Comment by dustymabe** [comment]
need to also cherry-pick 3eb1531 to update the manifest to F38

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by prestist — APPROVED** [review]
The flagged changes are expected. This changes are referencing the manifest f38 bump.

**Comment by prestist** [comment]
Downgrade detection triggered on `nmstate 2.2.9-2.fc37 -> 2.2.9-1.fc38` this can be ignored as in this case its [not a downgrade](https://github.com/coreos/fedora-coreos-config/pull/2375#discussion_r1167069982).

**Pull request merged**
