### PR TITLE
overrides: move to locking by source RPM

### PR DESCRIPTION
**Pull request by jlebon**
This is just much more natural and easier to maintain.

### CODE REVIEW

**Comment by jlebon** [comment]
This works on top of https://github.com/coreos/fedora-coreos-config/pull/884. (It doesn't strictly require it, but we can get that one in right now until this one is ready.)

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/rpm-ostree/pull/2680

**Review by travier — APPROVED** [review]

**Comment by jlebon** [comment]
And of course, this will also require tweaks to `coreos-koji-tagger` and `download-overrides.py` to support this.

**Comment by jlebon** [comment]
I was hacking on this and was pretty far along updating all of the GitHub Action, `download-overrides.py`, and `coreos-koji-tagger` to handle SRPMs correctly, but it's messy because SRPMs are pure strings in the RPM headers and not easy to work with in queries, etc... It also opens the door for correctly handling corner-cases like "what if an SRPM update also changes a binary RPM package name?".

Anyway, I think a good 80% of lockfile pain was addressed in https://github.com/coreos/fedora-coreos-config/pull/884. I think efforts are better spent improving other parts of the release process at this point.

**Pull request closed without merging**
