### PR TITLE
[testing-devel] overrides: drop everything

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Comment by dustymabe** [comment]
CI is failing with

```
+ curl -LO https://raw.githubusercontent.com/coreos/fedora-coreos-releng-automation/master/scripts/download-overrides.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2572  100  2572    0     0  15876      0 --:--:-- --:--:-- --:--:-- 15876
+ python3 download-overrides.py
Traceback (most recent call last):
  File "download-overrides.py", line 47, in <module>
    for pkg, pkgobj in lockfile['packages'].items():
AttributeError: 'NoneType' object has no attribute 'items'
script returned exit code 1
```

We might need to update the download-overrides script to handle an empty set of overrides.

**Comment by dustymabe** [comment]
> We might need to update the download-overrides script to handle an empty set of overrides.

remove the single `packages:` line from each file and just leave the single comment line in the file. That might fix it.

**Comment by sohankunkerkar** [comment]
> > We might need to update the download-overrides script to handle an empty set of overrides.
> 
> remove the single `packages:` line from each file and just leave the single comment line in the file. That might fix it.

Well, this didn't help. I think as you mentioned, we need to handle that condition in the download-overrides script.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-releng-automation/pull/114

**Comment by sohankunkerkar** [comment]
https://jenkins-coreos-ci.apps.ci.centos.org/blue/organizations/jenkins/github-ci%2Fcoreos%2Ffedora-coreos-config/detail/PR-489/6/pipeline/
Adding `packages: {}` to appease `rpm-ostree compose tree` test run.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by nikita-dubrovskii** [comment]
Actually this breaks multiarch build: ```Package 'crypto-policies' has (currently) unsupported <lua> script in '%post'```

**Comment by junjiequ** [comment]
> Actually this breaks multiarch build: `Package 'crypto-policies' has (currently) unsupported <lua> script in '%post'`

Same for me: `error: Package 'crypto-policies' has (currently) unsupported <lua> script in '%post'`, on **x86_64**...

**Comment by nikita-dubrovskii** [comment]
Ok, after rebuilding ```coreos-assembler image```  build works. Maybe it would be better to update ```Description```, so others are not confused with build failure

**Comment by junjiequ** [comment]
> Ok, after rebuilding `coreos-assembler image` build works. Maybe it would be better to update `Description`, so others are not confused with build failure

You have to build the cosa image yourself ? 
I guess the released version `v0.8.1` is not good enough to run fcos build anymore?

**Comment by bgilbert** [comment]
The `master` tag on quay.io should work fine.

**Comment by nikita-dubrovskii** [comment]
> You have to build the cosa image yourself ?

Yes, for s390x there is no image available

**Pull request merged**
