### PR TITLE
[stable] tree: promote changes from testing at 231e174b3a2f32aa28342e603ee066ae86a65e54

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @marmijo in https://github.com/coreos/fedora-coreos-streams/issues/733.

### CODE REVIEW

**Review by marmijo — DISMISSED** [review]

**Comment by marmijo** [comment]
CI is failing with 
```
cannot install both vim-data-2:9.0.1627-1.fc38.noarch from updates-archive and vim-data-2:9.0.1649-1.fc38.noarch from @System
```
Which seems to be related to https://github.com/coreos/fedora-coreos-tracker/issues/400
I'm investigating

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
I think the promotion diff CI check isn't working right because the `testing` branch PR already merged. Let's just ignore it. If the coreos-ci run passes let's merge this and start a build.

**Review by marmijo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
