### PR TITLE
overrides: fast-track kernel-5.18.4-201.fc36

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @dustymabe via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Comment by dustymabe** [comment]
Let's run the 5.18 kernel through our CI universe. It will get dropped into F36 eventually and I want to get a warm fuzzy that we are good.

Will revert this tomorrow.

**Review by dustymabe — DISMISSED** [review]
LGTM

**Comment by dustymabe** [comment]
I wanted to put this in as a fast track but IIUC overrides.py doesn't support fast-tracking anything that isn't a bodhi update (and I was too lazy to update the files manually). I plan on reverting this tomorrow anyway.

**Review by saqibali-2k — DISMISSED** [review]

**Comment by dustymabe** [comment]
hmm. Interesting.. the `testiso` `pxe-install` scenario is failing in CI for this. It appears that networking isn't coming up in the initramfs to be able to fetch remote resources.

**Comment by dustymabe** [comment]
> hmm. Interesting.. the `testiso` `pxe-install` scenario is failing in CI for this. It appears that networking isn't coming up in the initramfs to be able to fetch remote resources.

https://bugzilla.redhat.com/show_bug.cgi?id=2097165

**Comment by dustymabe** [comment]
The bug is fixed now in the last kernel update. Let's try it.

**Review by saqibali-2k — APPROVED** [review]

**Pull request merged**
