### PR TITLE
manifests/passwd: re-sync user entries with Fedora and sort them

### PR DESCRIPTION
**Pull request by lucab**
This updates users details in order to re-sync with the ones from Fedora packages.
It also sort all users by name, so that it is easier to diff against systemd-sysusers
output.

### CODE REVIEW

**Comment by dustymabe** [comment]
not sure if this is possible, but.. should we leave some sort of comment in here about how this syncing should be done in the future and also should we do it on some interval (like once a major Fedora release?)

**Comment by lucab** [comment]
In the future I hope that this file completely goes away, or at least it get mostly emptied out.

For the moment this syncing is a manual process, mostly based on other upstream&packaging fixes I've been doing recently. These are the sources for the three updates here:
 * https://src.fedoraproject.org/rpms/tpm2-tss/blob/rawhide/f/tpm2-tss-systemd-sysusers.conf
 * https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.14/bus/sysusers.d/dbus.conf.in#L5
 * https://github.com/systemd/systemd/blob/7238fd51d407043de1479211156e5fb412165416/sysusers.d/basic.conf.in#L13

**Comment by lucab** [comment]
There was one more missing, the GECOS field of the `root` user: https://pagure.io/setup/pull-request/43

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by jlebon — APPROVED** [review]

**Pull request merged**
