### PR TITLE
[testing] tree: promote changes from testing-devel at a8c84a3e055500ce8119535240f17e9e78fb1f4e

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by jlebon** [comment]
CI is printing:

```
+ jq .pkgdiff /srv/fcos/builds/latest/x86_64/meta.json
[
  [
    "curl-minimal",
    0,
    {
      "NewPackage": [
        "curl-minimal",
        "7.69.1-1.fc32",
        "x86_64"
      ]
    }
  ],
  [
    "libcurl-minimal",
    0,
    {
      "NewPackage": [
        "libcurl-minimal",
        "7.69.1-1.fc32",
        "x86_64"
      ]
    }
  ],
```

which is due to https://github.com/coreos/fedora-coreos-tracker/issues/454. I've just untagged f32 curl from the pool again for now, though I'm also working on getting https://github.com/coreos/rpm-ostree/pull/1858 and https://github.com/coreos/coreos-assembler/pull/1370 into cosa.

**Comment by dustymabe** [comment]
> though I'm also working on getting [coreos/rpm-ostree#1858](https://github.com/coreos/rpm-ostree/pull/1858) and [coreos/coreos-assembler#1370](https://github.com/coreos/coreos-assembler/pull/1370) into cosa.

we should wait on ^^ for this week's spin, right @jlebon ?

**Comment by sinnykumari** [comment]
latest ci run doesn't include curl-minimal and libcurl-minimal packages

**Comment by jlebon** [comment]
> we should wait on ^^ for this week's spin, right @jlebon ?

I think it'd be good, yeah. This is almost ready actually; just needs a final review and `/lgtm` on https://github.com/coreos/coreos-assembler/pull/1370 and then the patches mentioned in https://github.com/coreos/coreos-assembler/pull/1370#issuecomment-616575826.

If something doesn't work quite right yet with the new code, we can revert back to just making sure curl f32 stays tagged out and sanity-checking the diffs.

**Comment by jlebon** [comment]
I restarted CI again now that https://github.com/coreos/coreos-assembler/pull/1370 and https://github.com/coreos/coreos-ci-lib/pull/23 are in, but looks like we need to blow the Quay.io cache: https://github.com/coreos/coreos-assembler/pull/1377

**Comment by jlebon** [comment]
All green now, and diff looks good! In retrospect, I should've left the curl f32 package in the pool as a test. However, the previous CI run (without `--strict`) also had `libbrotli` from f32 added, and that's indeed gone too now.

There's another lockfile bump in https://github.com/coreos/fedora-coreos-config/pull/360 I think we wanted to get in before doing this release. And then I think we're good to go!

**Comment by dustymabe** [comment]
#360 merged and doing a testing-devel pipeline run now to confirm everything looks good

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
