### PR TITLE
kola-denylist: update mtu-on-bond test name

### PR DESCRIPTION
**Pull request by dustymabe**
The test name changed in bf37b9c.

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]
lgtm

**Review by jlebon — APPROVED** [review]
Do we need to also add the new networking test added in that commit as well?

**Review by saqibali-2k — APPROVED** [review]

**Comment by dustymabe** [comment]
> Do we need to also add the new networking test added in that commit as well?

no, IIUC it doesn't use any kargs that systemd-network-generator acts on.

**Comment by dustymabe** [comment]
skipping CI because it won't test this change.

**Pull request merged**
