### PR TITLE
manifest: add comments for removing nfs from dracut

### PR DESCRIPTION
**Pull request by dustymabe**
This will help us choose to keep or remove it in the future.

### CODE REVIEW

**Comment by dustymabe** [comment]
cc @jlebon to check for accuracy of statements

**Comment by jlebon** [comment]
Sure. Could also just have a one-liner that links to https://github.com/coreos/fedora-coreos-config/pull/60?

**Comment by dustymabe** [comment]
> Sure. Could also just have a one-liner that links to #60?

I often prefer to summarize the discussion because often linked to discussions can be lengthy, but you are right that we should also link to the original discussion. I added that.

**Comment by jlebon** [comment]
SGTM!

**Pull request merged**
