### PR TITLE
manifest: Move to Fedora Linux 37 content

### PR DESCRIPTION
**Pull request by dustymabe**
Also seeded the architecture specific lockfiles from `next-devel`.

### CODE REVIEW

**Review by jmarrero — DISMISSED** [review]
lgtm

**Comment by dustymabe** [comment]
Looks like CI will fail on this until next tuesday when F37 is released because the yum repos aren't quite ready yet.

**Comment by dustymabe** [comment]
ok CI should pass on this now. @jmarrero, can I get another round of review?

**Review by jmarrero — APPROVED** [review]

**Comment by dustymabe** [comment]
```
echo 'Downgrade detected. This is likely unintentional. If not, you may safely ignore this error.'
```

The one package that is being downgraded isn't a concern. I've sent a message to the package maintainer to see if we can get it pushed through in F37/Bodhi.

**Pull request merged**
