### PR TITLE
tree: promote changes from next-devel at ba427726157a7b7893c827869402…

### PR DESCRIPTION
**Pull request by travier**
…61856bbd8ed3

### CODE REVIEW

**Comment by travier** [comment]
Exited on error:
```
error: Couldn't find locked package 'btrfs-progs-5.9-1.fc33.x86_64' (pkgs matching NEVRA: 0; mismatched checksums: 0)
```
But I could not find any `createRepo` job in Koji so it does not look like the issue I hit with testing.

**Review by jlebon — APPROVED** [review]
LGTM!

**Comment by jlebon** [comment]
Had to jog the tagger. distRepo running now: https://koji.fedoraproject.org/koji/taskinfo?taskID=55807097. Edit: restarted CI!

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
