### PR TITLE
[next-devel] Fast-track multiple packages 

### PR DESCRIPTION
**Pull request by jlebon**
This matches `testing-devel`.

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm, I think we need some mechanism for sharing overrides more easily between `next-devel` and `testing-devel` during the phase in which they're the same (but while still allowing stream specific overrides).

**Comment by dustymabe** [comment]
Thanks @jlebon!

> Hmm, I think we need some mechanism for sharing overrides more easily between `next-devel` and `testing-devel` during the phase in which they're the same (but while still allowing stream specific overrides).

We could have a file in the next branch that tells config bot to sync them or not.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
> We could have a file in the next branch that tells config bot to sync them or not.

though, they are about to differ again soon: https://github.com/coreos/fedora-coreos-streams/issues/188#issuecomment-693688560

**Pull request merged**
