### PR TITLE
Move to Fedora 39 #1490

### PR DESCRIPTION
**Pull request by yasminvalim**
This PR, detailed in Issue [#1490](https://github.com/coreos/fedora-coreos-tracker/issues/1490) , follows the necessary steps to prepares for the upcoming Fedora CoreOS 39 GA release on October 30th by updating fedora-coreos-config.

### CODE REVIEW

**Comment by dustymabe** [comment]
> Fedora CoreOS 39 GA release on October 30th

The decision just came out as "No Go", so this will need to wait a week.

**Comment by yasminvalim** [comment]
> > Fedora CoreOS 39 GA release on October 30th
> 
> The decision just came out as "No Go", so this will need to wait a week.

Okay! But I have a question about it: 
So, we are not rebasing and release fedora 39, but it should have a regular release next week as usually have or not?

Thanks :)

**Comment by dustymabe** [comment]
> So, we are not rebasing and release fedora 39, but it should have a regular release next week as usually have or not?

Yep. We'll have a regular triple (`stable`,`testing`,`next`) release next week.

**Comment by jlebon** [comment]
Can you remove that stray merge commit?

Also, this isn't mentioned in the checklist, but let's also bump the other Dockerfiles in our tests that refer to Fedora 38.

**Comment by yasminvalim** [comment]
> Can you remove that stray merge commit?
> 
> Also, this isn't mentioned in the checklist, but let's also bump the other Dockerfiles in our tests that refer to Fedora 38.

Sure, I removed it. It took a while because I messed up with the interactive rebase. 
With other files should I look into besides /ci/continuous/Dockerfile? Should I change everything with the fedora 38 related?

**Comment by jlebon** [comment]
> Hmm, looks like there's a merge conflict now. Are you working from the latest `testing-devel`?

I think so, I rebased my branch so it supposed to be in the latest testing-devel. I fixed the conflicts, but I will check if everything is okay.

**Comment by yasminvalim** [comment]
@jlebon I made a new PR after trying to fix my branch and did not succeed. I will close this one, and let the other one ready to merge. Hope there is no problem with it.  

Here it is the new PR.  
https://github.com/coreos/fedora-coreos-config/pull/2719

Sorry about it.

**Comment by yasminvalim** [comment]
NEW PR: https://github.com/coreos/fedora-coreos-config/pull/2719

**Pull request closed without merging**
