### PR TITLE
[testing] tree: promote changes from testing-devel at 75c4b10

### PR DESCRIPTION
**Pull request by jlebon**
…41fc5f747245617

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm, sssd downgraded. Digging:

```
Downgraded:
  libipa_hbac 2.4.0-4.fc33 -> 2.3.1-4.fc33
  libsss_certmap 2.4.0-4.fc33 -> 2.3.1-4.fc33
  libsss_idmap 2.4.0-4.fc33 -> 2.3.1-4.fc33
  libsss_sudo 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-ad 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-client 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-common 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-common-pac 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-ipa 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-krb5 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-krb5-common 2.4.0-4.fc33 -> 2.3.1-4.fc33
  sssd-ldap 2.4.0-4.fc33 -> 2.3.1-4.fc33
```

**Comment by travier** [comment]
Last time something like that happened to me was because of a package going away / merged into an other one. Might not be the case here.

**Comment by jlebon** [comment]
So the commit where it downgraded was https://github.com/coreos/fedora-coreos-config/commit/44bfdaae8288b57a2860f804bddaf7eed49dbda5. This corresponds roughly with when https://bodhi.fedoraproject.org/updates/FEDORA-2021-b4adb66f7d was pushed to the repos. Somehow at the time the bump-lockfile job ran, the updates repo didn't have any sssd package, so it reverted to the one from the stable repo: https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/bump-lockfile/127/consoleFull

> ```
> sssd-2.3.1-4.fc33.x86_64 (fedora)
> sssd-ad-2.3.1-4.fc33.x86_64 (fedora)
> sssd-client-2.3.1-4.fc33.x86_64 (fedora)
> sssd-common-2.3.1-4.fc33.x86_64 (fedora)
> sssd-common-pac-2.3.1-4.fc33.x86_64 (fedora)
> sssd-ipa-2.3.1-4.fc33.x86_64 (fedora)
> sssd-krb5-2.3.1-4.fc33.x86_64 (fedora)
> sssd-krb5-common-2.3.1-4.fc33.x86_64 (fedora)
> sssd-ldap-2.3.1-4.fc33.x86_64 (fedora)
> ```

Anyway, let's hold this until we bump to the latest (2.4.1), but to do that we need https://github.com/coreos/coreos-assembler/pull/2046.

**Comment by jlebon** [comment]
OK, this is ready to go now!

**Review by travier — APPROVED** [review]

**Pull request merged**
