### PR TITLE
[stable] tree: promote changes from testing at d0379aac7423477b191545c0f6cc2145bd05dd43

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @saqibali-2k in https://github.com/coreos/fedora-coreos-streams/issues/454.

### CODE REVIEW

**Comment by dustymabe** [comment]
```patch
$ git diff upstreamtesting
diff --git a/manifest.yaml b/manifest.yaml
index fc5013f..7eba97c 100644
--- a/manifest.yaml
+++ b/manifest.yaml
@@ -1,4 +1,4 @@
-ref: fedora/${basearch}/coreos/testing
+ref: fedora/${basearch}/coreos/stable
 include: manifests/fedora-coreos.yaml
 
 releasever: "35"
@@ -6,7 +6,7 @@ releasever: "35"
 rojig:
   license: MIT
   name: fedora-coreos
-  summary: Fedora CoreOS testing
+  summary: Fedora CoreOS stable
 
 add-commit-metadata:
-  fedora-coreos.stream: testing
+  fedora-coreos.stream: stable
```

**Review by dustymabe — DISMISSED** [review]
LGTM

**Comment by saqibali-2k** [comment]
CI error: 
```
kola -p qemu-unpriv --output-dir /srv/fcos/tmp/fcosKola-D10lm/kola run --rerun --qemu-nvme=true basic
2022-02-14T18:49:34Z platform/conf: warnings parsing config: warning at $.storage.disks.0.partitions.1.label, line 13 col 18: incorrect partition number; a new partition will be created using reserved label
Error: Parsing config.ign: configured to treate config warnings as fatal
2022-02-14T18:49:34Z cli: Parsing config.ign: configured to treate config warnings as fatal
Traceback (most recent call last):
   File "/usr/lib/coreos-assembler/cmd-kola", line 65, in <module>
     subprocess.check_call(subargs)
   File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
     raise CalledProcessError(retcode, cmd)
 subprocess.CalledProcessError: Command '['kola', '-p', 'qemu-unpriv', '--output-dir', '/srv/fcos/tmp/fcosKola-D10lm/kola', 'run', '--rerun', '--qemu-nvme=true', 'basic']' returned non-zero exit status 1.

**Review by dustymabe — DISMISSED** [review]
LGTM

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
