### PR TITLE
[branched] overrides: fast-track selinux-policy-41.15-1.fc41

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Requested by @jbtrystram via [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/add-override.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/add-override.yml)).

### CODE REVIEW

**Comment by travier** [comment]
See: https://github.com/coreos/fedora-coreos-tracker/issues/1786

**Comment by dustymabe** [comment]
Can you run a test with this updated policy on s390x along with dropping the karg workaround in https://github.com/coreos/fedora-coreos-config/blob/ebeecf39e29992d0caea0ae8bee2ce8a58370f93/image.yaml#L6-L9

If that's successful then let's drop the karg workaround in this PR too? Should be able to revert that commit and push it up here to this PR.

We'll also revert and open a PR for rawhide too.

**Comment by jbtrystram** [comment]
Did a fresh build with this branch on s390x pod : 
```
--- PASS: basic (28.38s)
    --- PASS: basic/DbusPerms (0.29s)
    --- PASS: basic/ServicesActive (0.13s)
    --- PASS: basic/ReadOnly (0.12s)
    --- PASS: basic/Useradd (1.31s)
    --- PASS: basic/MachineID (0.13s)
    --- PASS: basic/FCOSGrowpart (0.13s)
    --- PASS: basic/PortSSH (0.12s)
```

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
