### PR TITLE
Updating next-devel manifest for f40

### PR DESCRIPTION
**Pull request by aaradhak**
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1674

### CODE REVIEW

**Review by dustymabe — DISMISSED** [review]
LGTM

**Comment by dustymabe** [comment]
though in order to get CI to pass I think you need to follow the step in https://github.com/coreos/fedora-coreos-tracker/issues/1674 to update the x86_64 lockfile.

**Comment by aaradhak** [comment]
> though in order to get CI to pass I think you need to follow the step in [coreos/fedora-coreos-tracker#1674](https://github.com/coreos/fedora-coreos-tracker/issues/1674) to update the x86_64 lockfile.

The manifest lockfile has been updated.

**Review by dustymabe — DISMISSED** [review]

**Comment by dustymabe** [comment]
and now CI is failing because of https://github.com/coreos/fedora-coreos-tracker/issues/1694

can you just drop the addition of the candidate compose repo here and we'll add it in a followup PR.

**Comment by dustymabe** [comment]
> can you just drop the addition of the candidate compose repo here and we'll add it in a followup PR.

or actually, just go ahead and add an override to pin on the old version of shim like I did in https://github.com/coreos/fedora-coreos-config/pull/2904

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by aaradhak** [comment]
> > can you just drop the addition of the candidate compose repo here and we'll add it in a followup PR.
> 
> or actually, just go ahead and add an override to pin on the old version of shim like I did in #2904

ok the overrides are added.

**Comment by aaradhak** [comment]
The kola test `ext.config.var-mount.scsi-id` fails in the CI.

**Comment by dustymabe** [comment]
> The kola test `ext.config.var-mount.scsi-id` fails in the CI.

guess we'll need to add `next` and `next-devel` to the list in the `kola-denylist.yaml` on the `testing-devel` branch. Open a new PR for that.

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
