### PR TITLE
[stable] tree: promote changes from testing at 58d067b6bb84d76080fbb6ac5acd0c75f9fbffcc

### PR DESCRIPTION
**Pull request by aaradhak**
This is created for testing purpose

### CODE REVIEW

**Comment by aaradhak** [comment]
Updated checkdiff fork - https://github.com/aaradhak/actions-lib/tree/checkdiff

**Comment by aaradhak** [comment]
@jlebon I am trying to test the changes in action lib repo where the python lib is installed in the Dockerfile. 

I have updated the workflow here to refer to the aaradhak/actions-lib. But the promotion diff action seem to get skipped. 

Would you know how to fix this ? Also, I wanted to check if we can test it this way?

**Comment by jlebon** [comment]
Likely triggering on https://github.com/coreos/fedora-coreos-config/blob/2984163685d3065ef4973b1dcbd5f33dbbc023a0/.github/workflows/promotion-diff.yml#L14. Try to change the PR title.

**Comment by HuijingHei** [comment]
/retitle tree: promote changes from testing aaradhak/actions-lib/tree/checkdiff

**Comment by HuijingHei** [comment]
> . Try to change the PR title.

Sorry @aaradhak  for the noise, according to Jonathan's comment, need to change the pull request title, not the title from UI.

**Pull request closed without merging**
