### PR TITLE
[testing] tree: promote changes from testing-devel at f9458601ee8fa05286fa5157bce952da029a249b

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @marmijo in https://github.com/coreos/fedora-coreos-streams/issues/982.

### CODE REVIEW

**Comment by dustymabe** [comment]
I had to add a commit to drop the fedora-bootc submodule temporarily as it was blocking CI and I don't understand why:

```
[2024-11-24T21:06:59.581Z] The recommended git tool is: git
[2024-11-24T21:07:02.355Z] using credential github-coreosbot-token-username-password
[2024-11-24T21:07:02.469Z] Warning: JENKINS-30600: special launcher org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1@61c8843a; decorates RemoteLauncher[hudson.remoting.Channel@7787fa36:JNLP4-connect connection from 10.129.3.250/10.129.3.250:40090] will be ignored (a typical symptom is the Git executable not being run inside a designated container)
[2024-11-24T21:07:02.473Z] Cloning the remote Git repository
[2024-11-24T21:07:02.473Z] Cloning with configured refspecs honoured and without tags
[2024-11-24T21:07:02.529Z] Cloning repository https://github.com/coreos/fedora-coreos-config.git
[2024-11-24T21:07:02.543Z]  > git init /home/jenkins/agent/workspace/fedora-coreos-config_PR-3279/config # timeout=10
[2024-11-24T21:07:02.568Z] Fetching upstream changes from https://github.com/coreos/fedora-coreos-config.git
[2024-11-24T21:07:02.568Z]  > git --version # timeout=10
[2024-11-24T21:07:02.630Z]  > git --version # 'git version 2.27.0'
[2024-11-24T21:07:02.630Z] using GIT_ASKPASS to set credentials GitHub coreosbot token as username/password
[2024-11-24T21:07:02.637Z]  > git fetch --no-tags --force --progress -- https://github.com/coreos/fedora-coreos-config.git +refs/pull/3279/head:refs/remotes/origin/PR-3279 +refs/heads/testing:refs/remotes/origin/testing # timeout=10
[2024-11-24T21:07:03.068Z]  > git config remote.origin.url https://github.com/coreos/fedora-coreos-config.git # timeout=10
[2024-11-24T21:07:03.074Z]  > git config --add remote.origin.fetch +refs/pull/3279/head:refs/remotes/origin/PR-3279 # timeout=10
[2024-11-24T21:07:03.078Z]  > git config --add remote.origin.fetch +refs/heads/testing:refs/remotes/origin/testing # timeout=10
[2024-11-24T21:07:03.574Z] Fetching without tags
[2024-11-24T21:07:03.734Z] Merging remotes/origin/testing commit 5f10a0e6c417bb40edf4626a778f057a4e10d0a8 into PR head commit 752c17bdb888cf1e0b160a6dbee6c2eae89dfde6
[2024-11-24T21:07:03.877Z] Merge succeeded, producing 752c17bdb888cf1e0b160a6dbee6c2eae89dfde6
[2024-11-24T21:07:03.877Z] Checking out Revision 752c17bdb888cf1e0b160a6dbee6c2eae89dfde6 (PR-3279)
[2024-11-24T21:07:04.150Z] Commit message: "tree: promote changes from testing-devel at f9458601ee8fa05286fa5157bce952da029a249b"
[2024-11-24T21:07:03.569Z]  > git config remote.origin.url https://github.com/coreos/fedora-coreos-config.git # timeout=10
[2024-11-24T21:07:03.577Z] Fetching upstream changes from https://github.com/coreos/fedora-coreos-config.git
[2024-11-24T21:07:03.577Z] using GIT_ASKPASS to set credentials GitHub coreosbot token as username/password
[2024-11-24T21:07:03.578Z]  > git fetch --no-tags --force --progress -- https://github.com/coreos/fedora-coreos-config.git +refs/pull/3279/head:refs/remotes/origin/PR-3279 +refs/heads/testing:refs/remotes/origin/testing # timeout=10
[2024-11-24T21:07:03.739Z]  > git config core.sparsecheckout # timeout=10
[2024-11-24T21:07:03.754Z]  > git checkout -f 752c17bdb888cf1e0b160a6dbee6c2eae89dfde6 # timeout=10
[2024-11-24T21:07:03.856Z]  > git remote # timeout=10
[2024-11-24T21:07:03.861Z]  > git config --get remote.origin.url # timeout=10
[2024-11-24T21:07:03.865Z] using GIT_ASKPASS to set credentials GitHub coreosbot token as username/password
[2024-11-24T21:07:03.866Z]  > git merge 5f10a0e6c417bb40edf4626a778f057a4e10d0a8 # timeout=10
[2024-11-24T21:07:03.872Z]  > git rev-parse HEAD^{commit} # timeout=10
[2024-11-24T21:07:03.879Z]  > git config core.sparsecheckout # timeout=10
[2024-11-24T21:07:03.883Z]  > git checkout -f 752c17bdb888cf1e0b160a6dbee6c2eae89dfde6 # timeout=10
[2024-11-24T21:07:04.152Z]  > git rev-list --no-walk 752c17bdb888cf1e0b160a6dbee6c2eae89dfde6 # timeout=10
[2024-11-24T21:07:04.174Z]  > git remote # timeout=10
[2024-11-24T21:07:04.231Z]  > git submodule init # timeout=10
Could not perform submodule update
```

**Comment by dustymabe** [comment]
Note: "Check promotion diffs" succeeded before the extra commit so I think we can ignore the failure here.

**Comment by c4rt0** [comment]
> Note: "Check promotion diffs" succeeded before the extra commit so I think we can ignore the failure here.

[link](https://github.com/coreos/fedora-coreos-config/actions/runs/11999565401/job/33447630055)

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Review by marmijo — APPROVED** [review]

**Pull request merged**
