### PR TITLE
[rhcos-4.15] overlay.d: add 40grub overlay

### PR DESCRIPTION
**Pull request by dustymabe**
bootupd upstream was modified to store default static grub configs and allow for OS integrators to add their own snippets by placing files in /usr/lib/bootupd/grub2-static/configs.d/ [1] When we move to building with osbuild we will start taking advantage of this functionality and calling bootupd with --with-static-configs. Let's go ahead and add our snippets here so they can be leveraged when we start calling bootupd with --with-static-configs.

The snippets added here come from the parts of the config currently defined in coreos-assembler that weren't lifted into bootupd [2][3][4].

[1] https://github.com/coreos/bootupd/pull/543
[2] https://github.com/coreos/coreos-assembler/blob/4636b1a5c6dc00b1d6a58b1bfbb199431444336b/src/grub.cfg#L58-L60
[3] https://github.com/coreos/coreos-assembler/blob/4636b1a5c6dc00b1d6a58b1bfbb199431444336b/src/grub.cfg#L71-L85
[4] https://github.com/coreos/coreos-assembler/blob/4636b1a5c6dc00b1d6a58b1bfbb199431444336b/src/grub.cfg#L87-L91

(cherry picked from commit b40f727e95b044201cde232a2ca64ec8a862b2ea)

### CODE REVIEW

**Comment by jmarrero** [comment]
this test seems to consistently fail:
```
[2024-01-05T12:34:47.101Z] --- FAIL: ext.config.ntp.timesyncd.dhcp-propagation (12.66s)

[2024-01-05T12:34:47.101Z]         harness.go:1818: mach.Start() failed: machine e694473b-4a57-4eb4-8cac-fc9d3e549f9a entered emergency.target in initramfs
```

**Comment by dustymabe** [comment]
yeah - FCOS tests shouldn't be running on RHCOS - let me cherry pick the disablement code that we always do on the branches here

**Comment by dustymabe** [comment]
pushed!

**Review by jmarrero — APPROVED** [review]
/lgtm

**Pull request merged**
