### PR TITLE
[stable] tree: promote changes from testing at e1ce9f2a55f46b6de565cb76e6d82adb157c68db

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @marmijo in https://github.com/coreos/fedora-coreos-streams/issues/895.

### CODE REVIEW

**Comment by dustymabe** [comment]
We need to cherry pick e1ce9f2 and add it as a second commit here.

**Comment by marmijo** [comment]
The manifest has been updated to set ` releasever` to Fedora 40.  The "check promotion diffs" failure is expected.

**Review by marmijo — APPROVED** [review]

**Review by dustymabe — APPROVED** [review]

**Comment by dustymabe** [comment]
LGTM - when we merge this let's make sure to keep in mind https://github.com/coreos/fedora-coreos-streams/issues/895#issuecomment-2088703443

**Comment by marmijo** [comment]
Sounds good, thanks for the reminder.

**Pull request merged**
