### PR TITLE
s390x: Fix ext.config.disks.partition-scheme

### PR DESCRIPTION
**Pull request by jschintag**
s390x only has 2 partitions. Adjust the test accordingly.

### CODE REVIEW

**Comment by jlebon** [comment]
Won't we break on the other arches next since they don't have `BIOS-BOOT`? Might as well fix those too while we're here and add the missing partitions (aarch64 has a reserved partition, and ppc64le has the prep boot partition and a reserved partition).

**Comment by dustymabe** [comment]
@jschintag if you want to make this easier for now just set this test to only run on x86_64 and will fix the others later. Sorry for breaking things.

**Comment by jschintag** [comment]
While i don't know about the partition layout on the other arches, i would like to point out that all the other arches passed the test in the pipeline. So i think adjusting it to also support s390x is the best way, instead of just disabling the test.
Tests for aarch64 and ppc64le:
https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/3094/
https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/3095/

**Comment by dustymabe** [comment]
It turns out that it actually is failing on the other arches, the failure just isn't being detected:

```
Dec 01 15:57:46 qemu0 kola-runext-partition-scheme[2113]: ++ jq 'select ( .name == "BIOS-BOOT") | .size'
Dec 01 15:57:47 qemu0 kola-runext-partition-scheme[2091]: + sectors=
Dec 01 15:57:47 qemu0 kola-runext-partition-scheme[2091]: /usr/local/bin/kola-runext-partition-scheme: line 45: * 512 : syntax error: operand expected (error token is "* 512 ")
Dec 01 15:57:47 qemu0 kola-runext-partition-scheme[2091]: + ok partition scheme
Dec 01 15:57:47 qemu0 kola-runext-partition-scheme[2091]: + echo ok partition scheme
Dec 01 15:57:47 qemu0 kola-runext-partition-scheme[2091]: ok partition scheme
Dec 01 15:57:47 qemu0 kola-runext-partition-scheme[2091]: + exit 0
```

**Comment by dustymabe** [comment]
What's weird is the encounter of the syntax error doesn't appear to stop the entire script from running, just the for loop so it drops down into the `ok()` and then exits 0.

**Comment by dustymabe** [comment]
I'll just merge this and try to fix it up.

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
