### PR TITLE
Prep patches for setting up branched/next-devel/next

### PR DESCRIPTION
**Pull request by jlebon**
Move the `releasever` key to `manifest.yaml`, and add branched development yum repo definitions.

### CODE REVIEW

**Comment by jlebon** [comment]
So basically, there's two ways to approach the "config" problem here: we could keep `testing-devel` as the "source branch" from which we propagate files to the next streams, or we could have `next-devel` be a separate source branch. The latter provides more flexibility, at the expense of more overhead. E.g. changing something that should apply to *both* `testing` and `next` will have to be opened twice against each respective source branch.

I'm leaning more towards the first approach for now (with `testing-devel` being the only source branch), given that IMO we will want the majority of changes to take effect on both `testing` and `next`. And as usual, anything specific to either can be added to their respective `manifest.yaml`.

**Comment by jlebon** [comment]
One hiccup where I see difficulties is if we want to carry something in the overlay only on one of the two streams. Right now, `overlay.d/` is purely a cosa concept, so there's no way to make it conditional if we have a single source branch.

I think it'd be cleaner if we folded the `overlay.d/` concept into the treefile (see related discussions in https://github.com/coreos/coreos-assembler/pull/639). Then we'd have the `manifest.yaml` be able to fully describe stream-level deltas.

Another cleanup from doing this is that intermediate manifests would be able to reference the overlays to which they "correspond". (E.g. `05core` would be in `fedora-coreos-base.yaml`, `15fcos` in `fedora-coreos.yaml`, etc... things that we're currently documenting in the [README.md](https://github.com/coreos/fedora-coreos-config/blob/2ee95eba30d38a7ef53c50ff52590ad1a27b92b6/overlay.d/README.md)).

**Comment by jlebon** [comment]
:telephone_receiver: ?
/cc @dustymabe @bgilbert

**Comment by dustymabe** [comment]
What is fedora-next.repo? Is it rawhide? Is it f31? If it's f31 then why not just let the releasever control it and use fedora.repo ?

**Comment by jlebon** [comment]
> What is fedora-next.repo?

It's the set of repos that `next` targets. So right now, f31.

> Is it f31? If it's f31 then why not just let the releasever control it and use fedora.repo ?

The paths are not the same yet.

**Comment by dustymabe** [comment]
> The paths are not the same yet.

right.. if we were using the metalink URLs it wouldn't matter but since we are using stable URLs (i.e. no mirrors) it does. Got ya.

**Comment by dustymabe** [comment]
this LGTM. Regarding the "managing the config" I'm afraid I don't have a good answer right now :(. In Fedora we use a branch for each release and then manually pull back stuff that we need. In this repo it's not always clear where the most development will be happening (i.e. not one clear upstream to everything like rawhide is in Fedora proper) so we'll have to organically come up with something that works for us.

**Review by dustymabe — APPROVED** [review]

**Comment by jlebon** [comment]
Will merge this after promoting for a release!

**Pull request merged**
