### PR TITLE
workflows/openshift-os allow custom branches

### PR DESCRIPTION
**Pull request by jbtrystram**
Allow specifying the source branch to open a PR from as well as the target branch to compare against.
This is useful for backporting work

### CODE REVIEW

**Review by yasminvalim — APPROVED** [review]
LGTM!

**Comment by dustymabe** [comment]
do we often sync from a branch other than `testing-devel` ?

**Comment by dustymabe** [comment]
I guess we do sync over to the release branches but we've been just doing that manually up until this point?

**Comment by jlebon** [comment]
A more streamlined/less error-prone tweak on this is to have it take a single input instead [of type `choice`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs) where you can choose an OCP release and it knows which f-c-c branch to open against which openshift/os branch.

**Comment by jbtrystram** [comment]
@jlebon yes, i thought of that, but we'd have to update this workflow file for each ocp release, that sounds like something we will forgot to do :)

**Comment by jlebon** [comment]
> @jlebon yes, i thought of that, but we'd have to update this workflow file for each ocp release, that sounds like something we will forgot to do :)

The default would just be e.g. `dev` or something to track `testing-devel` -> `master`. For branched releases, we have a checklist already of things to do that we could add to.

**Pull request merged**
