### PR TITLE
[stable] tree: promote changes from testing at 7d6d78cf804dfec53161ad8e7e6459affe9da75e

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @c4rt0 in https://github.com/coreos/fedora-coreos-streams/issues/756.

### CODE REVIEW

**Comment by dustymabe** [comment]
Keep in mind: https://github.com/coreos/fedora-coreos-streams/issues/756#issuecomment-1699870750

We need to make sure no kernel's get upgraded here.

**Comment by c4rt0** [comment]
Thanks for the reminder Dusty, I do keep that in mind.

**Review by c4rt0 — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
> Thanks for the reminder Dusty, I do keep that in mind.

Then you shouldn't have merged this?

**Comment by c4rt0** [comment]
I honestly thought you were referring to the next `build` stage. I'm so sorry 😞

**Comment by dustymabe** [comment]
That's OK. Just create a new commit and PR the `stable` branch :). At least we caught it before you started the build.

**Pull request merged**
