### PR TITLE
manifests: Move afterburn-dracut to shared system-configuration manifest

### PR DESCRIPTION
**Pull request by travier**
This sub package split will also be reflected in RHCOS.

### CODE REVIEW

**Comment by travier** [comment]
Hold to wait for approval from folks mentioned here.

**Review by sohankunkerkar — APPROVED** [review]
LGTM

**Review by jlebon — APPROVED** [review]

**Review by bgilbert — APPROVED** [review]
:+1:

We should hold until the split lands in RHCOS.

**Comment by travier** [comment]
Merged in https://github.com/coreos/fedora-coreos-config/pull/1372

**Pull request closed without merging**
