### PR TITLE
[next-devel] Revert "overrides: use grub2-2.06-98.fc39"

### PR DESCRIPTION
**Pull request by marmijo**
Now that there is a newer NVR version of grub2 (grub2-2.06-100.fc39) in the bodhi stable state than what is in Fedora 38 we can unpin the grub2 override that was necessary to prevent a downgrade in https://github.com/coreos/fedora-coreos-config/pull/2612#issuecomment-1722342103

This reverts commit 7ccc4f5c18804fa5e445f0f82a4758566a7deada.

### CODE REVIEW

**Comment by dustymabe** [comment]
> Now that the `next` stream has had a build based on Fedora 39, we can remove this pin.

I'm fine with leaving the commit message as is but I think the "reason" is a bit different than this.

i.e. something like this may be more appropriate:

Now that there is a newer NVR version of grub2 (grub2-2.06-100.fc39) in the bodhi stable state than what is in Fedora 38 we can unpin the grub2 override that was necessary to prevent a downgrade in https://github.com/coreos/fedora-coreos-config/pull/2612#issuecomment-1722342103

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by marmijo** [comment]
> i.e. something like this may be more appropriate:

Updated, along with the PR description. Thanks for also updating the title :smile:

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
