### PR TITLE
fedora-coreos-base: add in toolbox

### LINKED ISSUE #38: coreos/toolbox v2
We'd like to carry https://github.com/coreos/toolbox forward for FCOS and maybe give it a revamp as part of the process. Let's discuss design decisions for a v2 of coreos/toolbox in this ticket.

### PR DESCRIPTION
**Pull request by dustymabe**
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/38

### CODE REVIEW

**Comment by dustymabe** [comment]
IIUC toolbox does not currently handle all of our use cases but it will in the future so let's go ahead and include it so we can fix https://github.com/coreos/fedora-coreos-tracker/issues/38 and work through the issues.

**Comment by dustymabe** [comment]
Note that there is a current issue to work out but is being worked on: https://github.com/containers/toolbox/issues/267

**Comment by dustymabe** [comment]
weird CI issue:

```
[  436.104942] reboot: machine restart

New image input checksum: 7a3a60563ca2722e6a8ccfcfffc311f7f2648ff6f0b0fad7daa5da4d59644da4

None

New build ID: 30.20191016.dev.0

3226 metadata, 18856 content objects imported

parse error: Unmatched '}' at line 15, column 5

parse error: Unmatched '}' at line 26, column 44

script returned exit code 4
```

**Comment by dustymabe** [comment]
cc @cgwalters for input

**Comment by dustymabe** [comment]
also has anyone seen these deprecation warnings:

```
compose tree:305): librepo-WARNING **: 18:48:35.107: WARNING! Deprecated LRO_MIRRORLIST used


��� Updating metadata for 'fedora-coreos-pool' 100% 
```

**Comment by jlebon** [comment]
Yeah, they started appearing recently. Thought we maybe just needed a libdnf bump though that's not it (opened https://github.com/coreos/rpm-ostree/pull/1929 anyway). Haven't gotten around to investigating deeper yet.

> weird CI issue:

Hmm, yeah we've hit that in rpm-ostree CI too.

**Comment by jlebon** [comment]
Deprecation warnings addressed in https://github.com/rpm-software-management/libdnf/pull/819!

**Comment by dustymabe** [comment]
are we able to retrigger CI yet?

anyone opposed to merging this?

**Comment by jlebon** [comment]
The container is still rebuilding.

Do you have the final diff for this? (Or CI will give it to us once it's back up. Edit: ahh right, this needs https://github.com/coreos/fedora-coreos-config/pull/176)

**Comment by dustymabe** [comment]
The final diff is:

```
Added:
  flatpak-session-helper-1.4.3-1.fc30.x86_64
  toolbox-0.0.15-1.fc30.noarch
```

**Comment by dustymabe** [comment]
rebased on top of latest master

**Comment by cgwalters** [comment]
This makes sense, though I'd also like to land too
https://github.com/containers/toolbox/pull/303
so we could consider e.g. symlinking to coretoolbox from the same RPM for our use case, since it's known to work better, until we get things unified.

**Pull request merged**
