### PR TITLE
DNM: overlay: drop coreos-root in favor of tmpfiles

### PR DESCRIPTION
**Pull request by ajeddeloh**
Instead of using a systemd unit to populate /var/roothome use tmpfiles
entries.

Untested

### CODE REVIEW

**Comment by cgwalters** [comment]
LGTM if tested

**Comment by ajeddeloh** [comment]
Aside from needing `/usr/etc/skel` instead of `/etc/skel`, I'm hitting https://github.com/systemd/systemd/issues/12467 which is fixed by https://github.com/systemd/systemd/pull/12750 but that hasn't made it's way into fcos yet. The relative path solution there also doesn't work because tmpfiles disallows relative sources and if we hardcode `/sysroot/<path>` then we'll break when we _do_ pick up the fix.

**Comment by ajeddeloh** [comment]
retest this please

Ok, switched to symlinks. I intentionally used `/usr/etc/skel` instead of `/etc/skel` so people can't mistakenly edit the version the /etc by following the symlinks. Tested locally and it works fine.

**Review by arithx — APPROVED** [review]
Change LGTM (didn't test), once merged we should probably file a tracking issue for systemd 243 lands (to pick up systemd/systemd#12750) to update to `C!`

**Comment by dustymabe** [comment]
> once merged we should probably file a tracking issue for systemd 243 lands (to pick up [systemd/systemd#12750](https://github.com/systemd/systemd/pull/12750)) to update to `C!`

@ajeddeloh can you file that tracking bug and then merge this PR?

**Comment by jlebon** [comment]
Needs a `Closes: #136`, though I think we should hold this until we can use `C` instead of symlinks: https://github.com/coreos/fedora-coreos-config/issues/136#issuecomment-520606962

**Comment by ajeddeloh** [comment]
Hmm I'm on the fence on holding off until we can use `C!`. If we don't, we ought to roll this into `coreos-populate-var.service` since it's part of populating `/var`.

**Comment by ajeddeloh** [comment]
Opened https://github.com/coreos/fedora-coreos-config/pull/143 as a stopgap. Will rebase this once that merges, use C!, open a tracker ticket for it, and mark DNM until we can use C!.

**Comment by travier** [comment]
Closing in favor of https://github.com/coreos/fedora-coreos-config/pull/2556

**Pull request closed without merging**
