### PR TITLE
[stable] tree: promote changes from testing at 4d8450fa491d94f92330d6e162c1556310a61af0

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @prestist in https://github.com/coreos/fedora-coreos-streams/issues/720.

### CODE REVIEW

**Review by prestist — DISMISSED** [review]

**Review by dustymabe — DISMISSED** [review]
LGTM

**Comment by dustymabe** [comment]
CI is failing with: 

```
[2023-06-12T18:06:23.768Z] Running:  rpm-ostree compose container-encapsulate --max-layers=50 --format-version=1 --repo=/srv/coreos/tmp/repo --label=coreos-assembler.image-config-checksum=12fcea940941bb0fdfc7e693af5d5b80c20103cad5b2f7d1b325695c23e267bb --label=coreos-assembler.image-input-checksum=ba1355dc48ff181a51e8222b6b7a91a21c8d2565f244bdb66cff2964602a0383 --label=org.opencontainers.image.source=https://github.com/coreos/fedora-coreos-config.git --label=org.opencontainers.image.revision=dce709545516b8081ea2f95d8246a2b75b6a9df3 --copymeta-opt=fedora-coreos.stream --previous-build-manifest=/srv/coreos/builds/38.20230514.3.0/x86_64/fedora-coreos-38.20230514.3.0-ostree.x86_64-manifest.json 38.20230612.dev.0 oci-archive:fedora-coreos-38.20230612.dev.0-ostree.x86_64.ociarchive.tmp:latest

[2023-06-12T18:06:23.768Z] error: Found argument '--previous-build-manifest' which wasn't expected, or isn't valid in this context
```

Which is most likely related to https://github.com/coreos/coreos-assembler/pull/3445.

**Comment by dustymabe** [comment]
Opened a revert in https://github.com/coreos/coreos-assembler/pull/3506

**Comment by dustymabe** [comment]
Also restored the container image tag in quay to the previous version. I'll re-trigger CI now.

**Comment by dustymabe** [comment]
Cherry picked bc289de94648821928f12cb3316db11057f62d4b into this because CI was failing on that.

**Review by prestist — APPROVED** [review]
LGTM, @dustymabe Thank you for cherrypicking

**Pull request merged**
