### PR TITLE
[testing] tree: promote changes from testing-devel at 27ccdd05f3b0823340d6f2449b726a9aafffddd5

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @yasminvalim in https://github.com/coreos/fedora-coreos-streams/issues/978.

### CODE REVIEW

**Review by yasminvalim — APPROVED** [review]
lgtm

**Comment by dustymabe** [comment]
There is a releng issue that is preventing our builds (CI and pipeline) from succeeding right now. We will have to monitor https://pagure.io/koji/issue/4263

**Comment by yasminvalim** [comment]
> There is a releng issue that is preventing our builds (CI and pipeline) from succeeding right now. We will have to monitor https://pagure.io/koji/issue/4263

Thank you for sharing this with me. It seems this is blocking us— so should I wait until it’s resolved before continuing with the release?

**Comment by dustymabe** [comment]
> > There is a releng issue that is preventing our builds (CI and pipeline) from succeeding right now. We will have to monitor https://pagure.io/koji/issue/4263
> 
> Thank you for sharing this with me. It seems this is blocking us— so should I wait until it’s resolved before continuing with the release?

yes. we will have to wait for now

**Review by dustymabe — APPROVED** [review]

**Comment by dustymabe** [comment]
got the repo created - i'll start CI now

**Comment by dustymabe** [comment]
We'll have to get someone to look into why the promotions diffs CI is failing, but I think it's unrelated.

**Pull request merged**
