### PR TITLE
Move to Fedora Linux 38

### PR DESCRIPTION
**Pull request by dustymabe**
The Fedora 38 GA is to be released Tuesday April 18th.

### CODE REVIEW

**Comment by dustymabe** [comment]
looking at the CI failure I guess we can't switch it over officially until the prod repos are in place for 38 (probably late Monday or early Tuesday).

**Review by jlebon — DISMISSED** [review]

**Comment by dustymabe** [comment]
Ok this is ready for final review now.

**Review by jlebon — APPROVED** [review]
Verified diff against `next-devel`. Looks good.

**Comment by dustymabe** [comment]
CI fails due to downgrades being detected, but that's OK since we are switching to F38. The next `bump-lockfile` should update those packages so they would no longer be downgrades.

Merging.

**Pull request merged**
