### PR TITLE
[stable] tree: promote changes from testing at ffea42ea3ab8471b1c3b51a98b60685052164dc7

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Triggered by @sinnykumari in https://github.com/coreos/fedora-coreos-streams/issues/327.

### CODE REVIEW

**Comment by sinnykumari** [comment]
kola run failed:
```
Jun 14 08:05:56 qemu0 systemd[1]: Started kola-runext.service.
...
[2021-06-14T08:06:18.187Z] Jun 14 08:06:16 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
[2021-06-14T08:06:18.187Z] Jun 14 08:06:16 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
[2021-06-14T08:06:20.088Z] --- FAIL: ext.config.chrony.dhcp-propagation (49.31s)
[2021-06-14T08:06:20.088Z]         harness.go:717: kolet failed: : kolet run-test-unit failed: Error: Unit kola-runext.service exited with code 2
[2021-06-14T08:06:20.088Z] 2021-06-14T08:06:17Z cli: Unit kola-runext.service exited with code 2: Process exited with status 1
```

**Comment by sinnykumari** [comment]
cherry-picked PR https://github.com/coreos/fedora-coreos-config/pull/1056 to fix kola test run failure

**Review by sinnykumari — APPROVED** [review]

**Comment by dustymabe** [comment]
```diff
$ git diff upstreamtesting
diff --git a/manifest.yaml b/manifest.yaml
index f03556f..261e9dc 100644
--- a/manifest.yaml
+++ b/manifest.yaml
@@ -1,4 +1,4 @@
-ref: fedora/${basearch}/coreos/testing
+ref: fedora/${basearch}/coreos/stable
 include: manifests/fedora-coreos.yaml
 
 releasever: "34"
@@ -6,10 +6,10 @@ releasever: "34"
 rojig:
   license: MIT
   name: fedora-coreos
-  summary: Fedora CoreOS testing
+  summary: Fedora CoreOS stable
 
 repos:
   - fedora-coreos-pool
 
 add-commit-metadata:
-  fedora-coreos.stream: testing
+  fedora-coreos.stream: stable
diff --git a/tests/kola/chrony/dhcp-propagation b/tests/kola/chrony/dhcp-propagation
index 018af69..a097364 100755
--- a/tests/kola/chrony/dhcp-propagation
+++ b/tests/kola/chrony/dhcp-propagation
@@ -30,9 +30,12 @@ test_setup() {
 
     # run podman commands to set up dnsmasq server
     pushd $(mktemp -d)
-    NTPHOSTIP=$(getent hosts time-c-g.nist.gov | cut -d ' ' -f 1)
+    # XXX: hardcode IP for now until can resolve in CentOS CI again
+    #      https://pagure.io/centos-infra/issue/356
+    #NTPHOSTIP=$(getent hosts time-c-g.nist.gov | cut -d ' ' -f 1)
+    NTPHOSTIP='129.6.15.30'
     cat <<EOF >Dockerfile
-FROM registry.fedoraproject.org/fedora:33
+FROM registry.fedoraproject.org/fedora:34
 RUN dnf -y install systemd dnsmasq iproute iputils \
 && dnf clean all \
 && systemctl enable dnsmasq

```

LGTM

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
