### PR TITLE
manifest: Add `container-cmd`

### PR DESCRIPTION
**Pull request by cgwalters**
Builds on https://github.com/coreos/rpm-ostree/pull/3402

Relates to https://github.com/coreos/coreos-assembler/issues/2685

Basically, source of truth for the CMD moves from being hardcoded
in cosa hackiliy to being part of the ostree commit, which means
it survives a full round trip of
ostree → container → ostree → container

### CODE REVIEW

**Comment by cgwalters** [comment]
OK, rebased :surfer: and this should be good to merge now that we have a new enough rpm-ostree.

**Comment by cgwalters** [comment]
OK CI flaked on the journal bit, but this can't break kola tests anyways.

**Review by cheesesashimi — DISMISSED** [review]

**Comment by cheesesashimi** [comment]
Not sure If I have these perms for this repo, but I'll give it a try:

/lgtm
/approve

**Comment by jlebon** [comment]
Seems like this would be shared across all streams, right? In that case, maybe let's put it in `manifests/fedora-coreos.yaml` instead?

**Comment by cgwalters** [comment]
> Seems like this would be shared across all streams, right? In that case, maybe let's put it in manifests/fedora-coreos.yaml instead?

Ah yes, thank you!

**Review by jlebon — APPROVED** [review]

**Pull request merged**
