### PR TITLE
Send system journal logs to console

### PR DESCRIPTION
**Pull request by stbenjam**
When debugging early boot issues, especially ones that leave the host without functional networking, it's difficult to debug what broke. This change makes the default to send the systemd journal logs to the console on x86_64.  [We attempted to do this in openshift with a machineconfig](https://github.com/openshift/release/pull/38015), and this broke arm64 and this config was offered as an alternative.

### CODE REVIEW

**Comment by bgilbert** [comment]
Default kernel arguments are a last resort for configuration that really can't be done any other way.  If we want to do this, I think we should do it by adding a journald config file to the initrd instead.  But I'm not sure it's a good idea to do this everywhere.  Would it make sense to add this to debugging docs and leave the defaults as is?

**Comment by stbenjam** [comment]
I'm getting pointed many different directions by the coreos folks here.  We need the journal logs in CI, and I was asked to back out https://github.com/openshift/release/pull/38015, and this was the recommended approach by @travier

**Comment by cgwalters** [comment]
I don't think we should do this by default in FCOS/RHCOS, there'd be a lot of fallout.  One in particular is that today printing to the serial console can actually cause large system slowdown, and we explicitly did https://github.com/coreos/fedora-coreos-tracker/issues/1244 to avoid that for basic kernel logs.  This would *greatly* increase the output.

**Comment by cgwalters** [comment]
> this broke arm64 

link/more info?

> We need the journal logs in CI

Yes, but generally only on *failures*.  This relates to ye olde https://github.com/coreos/ignition/issues/585

**Comment by travier** [comment]
> I'm getting pointed many different directions by the coreos folks here. We need the journal logs in CI, and I was asked to back out [openshift/release#38015](https://github.com/openshift/release/pull/38015), and this was the recommended approach by @travier

OK, my bad, I hadn't realized that this was just for CI and not something more permanent.

**Comment by stbenjam** [comment]
> > this broke arm64
> 
> link/more info?
>

https://issues.redhat.com/browse/OCPBUGS-11812 is where it broke on ARM

> > We need the journal logs in CI
> 
> Yes, but generally only on _failures_. This relates to ye olde [coreos/ignition#585](https://github.com/coreos/ignition/issues/585)

I  don't think this would help since the failures were mysterious networking failures.  If there was something that if network never comes up, the journals got dumped the serial console might help.

**Pull request closed without merging**
