### PR TITLE
kola: split misc-ign-ro into indivudal tests

### PR DESCRIPTION
**Pull request by mike-nguyen**
Now that kola has the ability to run non-exclusive tests, split out the
remaining misc-ign-ro tests for better reporting and more granular
control of running tests.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
The shared library will need these fixes https://github.com/coreos/coreos-assembler/pull/2557 and https://github.com/coreos/coreos-assembler/pull/2556.  I'll do the shared library in a follow-up PR

**Review by dustymabe — DISMISSED** [review]
LGTM - one NIT on the commit message: `s/misc-ro-ign/misc-ign-ro/`

**Comment by mike-nguyen** [comment]
Commit messaged updated

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
