### PR TITLE
tests: Add basic test for rpm-ostree countme

### PR DESCRIPTION
**Pull request by travier**
Test that:
- The timer is started when rpm-ostreed started
- Manual startup of the count me service is sucessful

### CODE REVIEW

**Comment by travier** [comment]
This will obviously fail until we enable rpm-ostree count me support in FCOS.

I made this into an independent test but maybe this could be part of misc-ro? (even though this touches the file-system to store the count me cookie and needs internet access).

**Comment by cgwalters** [comment]
The test can include an Ignition config which explicitly enables it at least right?

**Comment by travier** [comment]
This one is pending the inclusion of the new rpm-ostree release.

**Comment by cgwalters** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2021-6e1df8e4ab and https://github.com/coreos/fedora-coreos-config/commit/cb58430ffdbf05f20339eca7539be7f23b0fb999 are done now.

**Comment by travier** [comment]
This one needs a LGTM 🙂

**Comment by cgwalters** [comment]
```
-- Logs begin at Wed 2021-04-07 01:17:15 UTC, end at Wed 2021-04-07 01:17:44 UTC. --
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1226]: ++ systemctl show -p ActiveState rpm-ostree-countme.timer
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: + [[ ActiveState=active != \A\c\t\i\v\e\S\t\a\t\e\=\a\c\t\i\v\e ]]
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: + systemctl start rpm-ostree-countme.service
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1231]: ++ systemctl show -p ActiveState rpm-ostree-countme.service
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: + [[ ActiveState=inactive != \A\c\t\i\v\e\S\t\a\t\e\=\i\n\a\c\t\i\v\e ]]
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1236]: ++ jq --raw-output .MESSAGE
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1235]: ++ journalctl --output=json --boot --unit=rpm-ostree-countme.service --grep 'Successful requests:'
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: + [[ Successful requests: 2/2 != \S\u\c\c\e\s\s\f\u\l\ \r\e\q\u\e\s\t\s\:\ \2\/\2 ]]
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: + ok countme
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: + echo ok countme
Apr 07 01:17:41 qemu0 kola-runext-test.sh[1225]: ok countme
```

**Review by cgwalters — APPROVED** [review]

**Pull request merged**
