### PR TITLE
manifest-lock.overrides: Drop selinux-policy & systemd pins

### PR DESCRIPTION
**Pull request by travier**
manifest-lock.overrides: Drop selinux-policy pin

---

manifest-lock.overrides: Drop systemd 255 pin

---

Let's see if we've made enough progress on:
- https://github.com/coreos/fedora-coreos-tracker/issues/1735
- https://bugzilla.redhat.com/show_bug.cgi?id=2292472

### CODE REVIEW

**Comment by travier** [comment]
This is an updated version of https://github.com/coreos/fedora-coreos-config/pull/3010

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
With this, if I run `cosa run --devshell-console`, then I get a shell, and I can also ssh to the system from itself.
If I run `cosa run --devshell`, kola can not connect to the system via ssh.

**Comment by travier** [comment]
Ah, I had a local override. Doing a new build.

**Comment by aaradhak** [comment]
Recently we did a test with the updated copr build for selinux-policy that failed , adding here for reference: https://github.com/coreos/fedora-coreos-config/pull/3072

**Comment by marmijo** [comment]
Closing this with some follow up info:
- the selinux-policy issue was resolved: https://github.com/coreos/fedora-coreos-tracker/issues/1735
  - pin removed from `rawhide`
    -  https://github.com/coreos/fedora-coreos-config/pull/3102
  - pin removed from `branched`
    -  https://github.com/coreos/fedora-coreos-config/pull/3092
  
-  A systemd-256 issue is still ongoing, so the pin on systemd-255 is still necessary
    -  potentially: https://github.com/coreos/fedora-coreos-tracker/issues/1775

**Pull request closed without merging**
