### PR TITLE
overrides: drop grub2 pin, bump to 2.06-72.fc37

### PR DESCRIPTION
**Pull request by jlebon**
Issue #1352 is now fixed in the latest grub2 in f37 as per https://github.com/coreos/fedora-coreos-tracker/issues/1352#issuecomment-1371225262.

### CODE REVIEW

**Comment by dustymabe** [comment]
That version of grub2 is already in the Fedora `stable` bodhi repos so let's just delete the files to drop the override instead?

**Comment by jlebon** [comment]
Yeah, I debated doing that. If we delete it, an immediate build would still respect the base lockfile containing the old grub2 and we wouldn't have the bump until bump-lockfile runs. Doing it this way means CI actually tests the new grub2 package.

**Comment by dustymabe** [comment]
does the override graduating code handle the arch specific overrides files? If it doesn't then maybe just hand edit the generated lockfiles in this PR too and delete the arch specific overrides files. I just don't want to make more work for ourselves than we need to.

**Comment by jlebon** [comment]
It doesn't currently. Updated to bump base lockfiles directly!

**Comment by dustymabe** [comment]
From the commit message:

> Issue #1352 is now fixed in the latest grub2 in f37 as per

In the GitHub web UI this points us at https://github.com/coreos/fedora-coreos-config/pull/1352 which is not what you wanted. Can you either give it a full identifier or remove the reference (the later link suffices).

**Review by dustymabe — DISMISSED** [review]
one optional suggestion.

LGTM

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
