### PR TITLE
manifests: add passt

### PR DESCRIPTION
**Pull request by PhrozenByte**
See: https://github.com/coreos/fedora-coreos-tracker/issues/1436

### CODE REVIEW

**Comment by PhrozenByte** [comment]
No idea whether the lockfiles are correct this way (no idea whether I've fiddled with them the way it's expected), but the workflow still fails. However, the failure doesn't seem to be related to `passt`, but some other package (`shim`)?

**Comment by dustymabe** [comment]
I added a basic test for `--net=pasta` functionality.

**Review by jlebon — APPROVED** [review]
Didn't realize `^` was a valid character in RPM versioning. Will be interesting to see if anything breaks because of this.

**Comment by sbrivio-rh** [comment]
Thank you so much @PhrozenByte and @dustymabe! I didn't see this until now.

**Pull request merged**
