### PR TITLE
tree: promote changes from testing-devel at d3b642734e70a785133639ce3344e815da9e3fd0

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Review by jlebon — APPROVED** [review]

**Comment by jlebon** [comment]
Hmm, CI failing to find some packages. I restarted it to make sure. There was another occurrence recently where somehow some packages were untagged from the pool so it might be that again.

**Comment by sinnykumari** [comment]
You are right, it seems required  new updates for kernel ([5.5.5-200.fc31.x86_64](https://koji.fedoraproject.org/koji/buildinfo?buildID=1466605)), selinux-policy([3.14.4-48.fc31.noarch](https://koji.fedoraproject.org/koji/buildinfo?buildID=1462422)) and skopeo([1:0.1.41-1.fc31.x86_64](https://koji.fedoraproject.org/koji/buildinfo?buildID=1461505)) are not yet tagged in coreos-pool

**Comment by jlebon** [comment]
This turned out to be due to https://github.com/coreos/fedora-coreos-releng-automation/issues/70.

**Pull request merged**
