### PR TITLE
tests/kola: Rename config files from .fcc to .bu

### PR DESCRIPTION
**Pull request by gursewak1997**
tests/kola: Rename .fcc config files to .bu

Issue: https://github.com/coreos/coreos-assembler/issues/2456

### CODE REVIEW

**Comment by bgilbert** [comment]
One of the files got renamed to `config.butane` for some reason.

**Review by bgilbert — APPROVED** [review]
LGTM

**Review by saqibali-2k — APPROVED** [review]
:+1:

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
