### PR TITLE
s390x: Skip incompatible kola tests

### PR DESCRIPTION
**Pull request by jschintag**
Skip tests that are new and currently failling on s390x. These tests need further investigation wether or not they can be adapted on s390x.
Also skip grub specific part of the reboot test, as s390x does not use grub.

### CODE REVIEW

**Review by mike-nguyen — DISMISSED** [review]
LGTM

**Comment by dustymabe** [comment]
Hey @jschintag - can you add a reason for adding that argument to each kola.json fragment? If we need more investigation can we open an issue to track that and link to it?

**Comment by dustymabe** [comment]
Here's an example of doing that:

https://github.com/coreos/fedora-coreos-config/blob/d75822c6c17d1dd0847719c603700e42f1774fe1/tests/kola/root-reprovision/luks/test.sh#L8-L9

**Comment by jschintag** [comment]
> Hey @jschintag - can you add a reason for adding that argument to each kola.json fragment? If we need more investigation can we open an issue to track that and link to it?

@dustymabe I added the comments to the kola.json fragments. The Issues for this are:
https://github.com/coreos/fedora-coreos-config/issues/1499 Network Manager Issue
https://github.com/coreos/fedora-coreos-tracker/issues/1267 kdump.service not working

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by miabbott — APPROVED** [review]
LGTM

**Review by jlebon — APPROVED** [review]

**Comment by travier** [comment]
Sorry for being late here, bur are all of those tests really incompatible on s390x? If the test are only "not working" right now for some unknown reasons, they should probably end up in the kola-denylist instead. I think that at least the kdump test is in this case.

**Comment by dustymabe** [comment]
I'm OK with denylist entries instead. Either way I think (hopefully) we'll find real reasoning in the investigation in coreos/fedora-coreos-config#1499 and coreos/fedora-coreos-tracker#1267

**Comment by jschintag** [comment]
I put the restriction into the tests for now, as they haven't to my knowledge ever worked on s390x.
Therefore i see the 2 Issues more as a development item rather than a bug fix.

**Pull request merged**
