### PR TITLE
tree: promote changes from testing-devel at 44951ad75164

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
All looks like expected changes from development so far; LGTM!

**Comment by cgwalters** [comment]
> error: Packages not found: fuse-overlayfs, kernel-core, microcode_ctl, openssl, whois-nls

Hm, something going wrong with lockfiles?

**Comment by bgilbert** [comment]
retest this please

**Comment by bgilbert** [comment]
coreos-koji-tagger fell over and those builds weren't tagged into the pool.  I've tagged them all in, which fixed `fuse-overlayfs`, but the others are still failing for some reason.

**Comment by bgilbert** [comment]
I had run the tagger twice, not realizing that there's a delay between adding a package to the intermediate tag and koji adding them to the target tag.  The result was two sets of tagging tasks, which apparently spawned repo regeneration tasks that raced with each other and resulted in a stale repo.  To address this, `koji regen-repo` didn't work for me, so I untagged and retagged a package from `coreos-pool` and the resulting regen task fixed the repo.

**Comment by dustymabe** [comment]
> coreos-koji-tagger fell over and those builds weren't tagged into the pool. 

Do you have any logs from it failing? I'm looking at the logs now but it looks like the container was restarted and previous logs are gone.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by bgilbert** [comment]
> Do you have any logs from it failing? I'm looking at the logs now but it looks like the container was restarted and previous logs are gone.

Nope.  I don't actually seem to have access to Fedora OpenShift.  :slightly_frowning_face:

**Comment by jlebon** [comment]
>  The result was two sets of tagging tasks, which apparently spawned repo regeneration tasks that raced with each other and resulted in a stale repo.

Ahh yup, that's https://pagure.io/koji/issue/1630.

**Comment by dustymabe** [comment]
> Nope. I don't actually seem to have access to Fedora OpenShift. slightly_frowning_face

This should help. https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=371f02c8d617e2d0f698fe63c2aa56953f18bdd0

Next time you should be able to browse https://os.fedoraproject.org/console/project/coreos-koji-tagger/overview

**Pull request merged**
